#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
from os.path import join as pjoin
from os.path import dirname, abspath, normpath, basename
import time
import shlex

import libvvtest.cmdline as cmdline
from libvvtest.execlist import TestExecList
from libvvtest.testrunner import TestRunner
import libvvtest.pathutil as pathutil
from libvvtest.errors import FatalError
import libvvtest.location as location
import libvvtest.execute as execute
import libvvtest.TestList as TestList


version = '1.2'

search_fnmatch = ['*.inp','*.apr','*.i']

USER_PLUGIN_MODULE_NAME = 'vvtest_user_plugin'


class MainEntry:

    def __init__(self, argv, vvtestdir, exepath):
        """
        'vvtestdir' is the (real) directory containing the vvtest script
        """
        self.argv = argv
        self.vvtestdir = vvtestdir
        self.exepath = exepath
        self.curdir = os.getcwd()

        self.rtdata = RuntimeData( self.curdir, self.exepath )

    def constructObjects(self):
        ""
        self.start_epoch = time.time()

        check_load_bootstrap_file( self.curdir, self.exepath )

        # this may call sys.exit (for help or errors)
        self.opts, self.optD, self.dirs = \
            cmdline.parse_command_line( self.argv[1:], version )

        construct_locator( self.rtdata, self.opts )

        configdirs = self.rtdata.loc.getConfigDirs( self.opts.config )

        insert_configdirs_into_sys_path( self.vvtestdir, configdirs )

        construct_runtime_config( self.rtdata, self.opts, self.optD )

        construct_and_process_cache_file( self.rtdata, self.opts, self.optD )

        construct_runtime_info( self.rtdata, self.argv, self.vvtestdir,
                                self.opts, self.start_epoch )

        create_configuration( self.rtdata.rtconfig, self.opts, self.optD,
                              self.vvtestdir, configdirs )

        # this is scheduled for deprecation
        if self.opts.check:
            for n in self.opts.check:
                os.environ[ 'CHECK_' + n.upper() ] = ''

        construct_platform( self.rtdata, self.vvtestdir, self.opts, self.optD )

        construct_testcase_constructor( self.rtdata, self.opts )

        compute_testing_directory( self.rtdata, self.opts, self.optD )

        construct_permission_setter( self.rtdata, self.opts )

        construct_results_writers( self.rtdata, self.opts, self.optD )

        construct_testcase_creator( self.rtdata )

        construct_test_scanner( self.rtdata, self.dirs, self.opts, self.optD )

        import_plugin_module( self.rtdata )

        construct_test_selector( self.rtdata )

        construct_test_time_handler( self.rtdata, self.opts )

        construct_test_list_manager( self.rtdata )

    def execute(self):
        ""
        exitstat = 0

        tlm = self.rtdata.tlm

        if information_mode( self.opts ):
            exitstat = information_output( self.opts, self.optD,
                                           self.rtdata, tlm )

        elif self.opts.dash_g:
            generateTestList( self.opts, self.optD, self.rtdata, tlm )

        elif self.opts.dash_b:

            if self.opts.dash_R or self.opts.dash_w:
                raise FatalError( 'cannot use -R or -w with -b (baseline)' )

            baselineTests( self.opts, self.optD, self.rtdata, tlm )

        elif self.opts.extract:
            extractTestFiles( self.opts.scan_type,
                              self.optD['param_dict'],
                              self.opts.extract, self.rtdata, tlm )

        else:

            # if no results keywords are specified, then add -k notrun/notdone
            if not self.opts.dash_w and not self.opts.dash_R:
                rtconfig = self.rtdata.rtconfig
                rtconfig.addResultsKeywordExpression( 'notrun or notdone' )

            if self.rtdata.isrestart:
                exitstat = restartTests( self.opts, self.optD, self.rtdata, tlm )
            else:
                exitstat = runTests( self.opts, self.optD, self.rtdata, tlm )

        if self.opts.encode_exit_status:
            return exitstat


class RuntimeData:
    def __init__(self, curdir, exepath):
        ""
        self.curdir  = curdir   # current working directory at vvtest startup
        self.exepath = exepath  # path to vvtest (without following soft link)

        self.testdir        = None   # top level test execution directory
        self.cash           = None   # CacheFileHandler object
        self.rtinfo         = None   # RuntimeInfo object
        self.plat           = None   # Platform object
        self.rtconfig       = None   # RuntimeConfig object
        self.plugin         = None   # UserPluginBridge object
        self.isrestart      = False  # True if inside a test results tree
        self.perms          = None   # Permissions object
        self.results_writer = None   # ResultsWriters object
        self.tctor          = None   # TestConstructor object
        self.creator        = None   # TestCreator object
        self.scanner        = None   # TestFileScanner object
        self.selector       = None   # TestSelector object
        self.tlm            = None   # TestListManager object


def construct_locator( rtdata, opts ):
    ""
    rtdata.loc = location.Locator( rtdata.curdir, opts.dash_M, opts.dash_w )


def construct_runtime_config( rtdata, opts, optD ):
    ""
    from libvvtest.RuntimeConfig import RuntimeConfig

    rtconfig = RuntimeConfig()

    rtconfig.setPlatformExpression( optD['platform_expr'] )
    if opts.dash_A:
        rtconfig.applyPlatformExpression( False )
    rtconfig.setKeywordExpression( optD['keyword_expr'] )
    rtconfig.setParameterExpression( optD['param_list'] )
    rtconfig.setIncludeTDD( opts.include_tdd == True )
    rtconfig.setFileSearch( optD['search_regexes'], search_fnmatch )
    rtconfig.setRuntimeRange( opts.tmin, opts.tmax )
    rtconfig.setRuntimeSum( opts.tsum )

    rtdata.rtconfig = rtconfig


def construct_and_process_cache_file( rtdata, opts, optD ):
    ""
    rtdata.cash = CacheFileHandler( opts, optD, rtdata.rtconfig )

    # non-None only if the CWD is in a TestResults.* directory
    cache_file = rtdata.loc.findCacheFile()

    if cache_file:
        is_restart = True
        rtdata.cash.setCacheFilename( dirname( cache_file ) )
        check_options_not_allowed_for_restart( opts, optD )
        rtdata.cash.readCache()
    else:
        is_restart = False

    rtdata.isrestart = is_restart


def check_options_not_allowed_for_restart( opts, optD ):
    ""
    if optD['onopts'] or optD['offopts'] or opts.dash_g:
        raise FatalError( 'the -g, -o, and -O options are not allowed '
                          'in a TestResults directory')

    if optD['param_dict']:
        raise FatalError( 'cannot use -S in a TestResults directory' )

    if opts.dash_g:
        raise FatalError( 'cannot use -g in a TestResults directory' )


def construct_runtime_info( rtdata, argv, vvtestdir, opts, start_epoch ):
    ""
    from libvvtest.runinfo import RuntimeInfo

    rtinfo = RuntimeInfo( startepoch=start_epoch,
                          cmdline=argv,
                          vvtestdir=vvtestdir,
                          curdir=rtdata.curdir )

    if opts.short_xdirs:
        rtinfo.setInfo( shortxdirs=opts.short_xdirs )

    rtdata.rtinfo = rtinfo


def create_configuration( rtconfig, opts, optD, vvtestdir, configdirs ):
    ""
    rtconfig.setAttr( 'vvtestdir', vvtestdir )

    if optD['onopts']:
        rtconfig.setAttr( 'onopts', optD['onopts'] )
    if optD['offopts']:
        rtconfig.setAttr( 'offopts', optD['offopts'] )

    if opts.bin_dir:
        rtconfig.setAttr( 'exepath', opts.bin_dir )

    rtconfig.setAttr( 'configdir', configdirs )

    rtconfig.setAttr( 'refresh', not opts.dash_m )
    rtconfig.setAttr( 'postclean', opts.postclean == True )

    if opts.dash_T != None:
        rtconfig.setAttr( 'timeout', opts.dash_T )
    if opts.timeout_multiplier != None:
        rtconfig.setAttr( 'multiplier', opts.timeout_multiplier )

    rtconfig.setAttr( 'preclean', not opts.dash_m )
    rtconfig.setAttr( 'analyze', opts.analyze == True )
    rtconfig.setAttr( 'logfile', not opts.dash_L )

    if opts.test_args:
        argL = []
        for args in opts.test_args:
            argL.extend( shlex.split( args ) )
        rtconfig.setAttr( 'testargs', argL )


def construct_platform( rtdata, vvtestdir, opts, optD ):
    ""
    import libvvtest.vvplatform as vvplatform

    plat = vvplatform.create_Platform_instance(
                vvtestdir,
                opts.plat, opts.batch,
                optD['platopt_dict'],  # --platopt
                opts.dash_e,
                opts.dash_n,
                opts.dash_N,
                opts.devices,
                opts.max_devices,
                optD['onopts'],        # -o
                optD['offopts'] )      # -O

    rtdata.rtconfig.setPlatformName( plat.getName() )
    rtdata.rtconfig.setOptionList( optD['onopts'] + [plat.getCompiler()] )
    rtdata.rtconfig.setMaxSize( plat.getMaxSize() )

    rtdata.rtinfo.setInfo( platform=plat.getName(),
                           compiler=plat.getCompiler() )

    rtdata.plat = plat


def construct_testcase_constructor( rtdata, opts ):
    ""
    from libvvtest.testctor import TestConstructor

    tctor = TestConstructor()

    # magic: check and print error if this fails to cast to int
    if opts.short_xdirs:
        tctor.setShorten( int( opts.short_xdirs ) )

    rtdata.tctor = tctor


def compute_testing_directory( rtdata, opts, optD ):
    ""
    td = rtdata.loc.setTestingDirectory( opts.run_dir,
                                         optD['onopts'],
                                         optD['offopts'],
                                         rtdata.plat.getName() )

    rtdata.cash.setCacheFilename( td )
    rtdata.rtinfo.setInfo( rundir=td )
    rtdata.testdir = td


def construct_permission_setter( rtdata, opts ):
    ""
    if opts.perms:
        from libvvtest.permsetter import PermissionSetter
        perms = PermissionSetter( rtdata.testdir, opts.perms )

    else:
        class DummyPermissionSetter:
            def __init__(self): pass
            def set(self, path): pass
            def recurse(self, path): pass

        perms = DummyPermissionSetter()

    rtdata.perms = perms


def construct_testcase_creator( rtdata ):
    ""
    from libvvtest.testcreator import TestCreator

    creator = TestCreator( rtdata.rtconfig.getPlatformName(),
                           rtdata.rtconfig.getOptionList(),
                           rtdata.tctor )

    rtdata.creator = creator


def construct_test_scanner( rtdata, scandirs, opts, optD ):
    ""
    from libvvtest.scanner import TestFileScanner

    if len( scandirs ) == 0:
        # scan current working directory by default
        scandirs.append( rtdata.curdir )

    scanner = TestFileScanner( rtdata.creator, scandirs,
                               force_params_dict=optD['param_dict'],
                               spectype=opts.scan_type )

    rtdata.scanner = scanner


def import_plugin_module( rtdata ):
    ""
    import libvvtest.userplugin as userplugin

    try:
        plugmod = userplugin.import_module_by_name( USER_PLUGIN_MODULE_NAME )

    except userplugin.UserPluginError:
        print3( '*** error in user plugin script:',
                str( sys.exc_info()[1] ).strip() )
        print3( '*** user plugin disabled\n' )
        plugmod = None

    plug = userplugin.UserPluginBridge( rtdata.rtconfig, plugmod )

    rtdata.plugin = plug


def construct_test_selector( rtdata ):
    ""
    from libvvtest.filtering import TestFilter
    from libvvtest.testselector import TestSelector

    testfilter = TestFilter( rtdata.rtconfig, rtdata.plugin )

    tsel = TestSelector( rtdata.testdir, testfilter, rtdata.creator )

    rtdata.selector = tsel


def construct_test_time_handler( rtdata, opts ):
    ""
    from libvvtest.timeout import TimeHandler

    tcache = construct_runtime_lookup_cache( rtdata.plat )

    timehandler = TimeHandler( rtdata.plugin,
                               opts.dash_T,
                               opts.timeout_multiplier,
                               opts.max_timeout,
                               tcache )

    rtdata.timehandler = timehandler


def construct_runtime_lookup_cache( plat ):
    ""
    from libvvtest.fmtresults import LookupCache

    pname = plat.getName()
    cplr = plat.getCompiler()
    tdir = plat.testingDirectory()

    cache = LookupCache( pname, cplr, tdir )

    return cache


def construct_test_list_manager( rtdata ):
    ""
    from batch.namer import BatchFileNamer
    namer = BatchFileNamer( rtdata.testdir )

    rtdata.tlm = TestListManager( locator=rtdata.loc,
                                  namer=namer,
                                  tctor=rtdata.tctor,
                                  scanner=rtdata.scanner,
                                  selector=rtdata.selector,
                                  timehandler=rtdata.timehandler,
                                  cachehandler=rtdata.cash,
                                  rtinfo=rtdata.rtinfo,
                                  perms=rtdata.perms )


class TestListManager:

    def __init__(self, locator, namer, tctor, scanner,
                       selector, timehandler, cachehandler,
                       rtinfo, perms):
        ""
        self.tlist = None

        self.locator = locator
        self.namer = namer
        self.tctor = tctor
        self.scanner = scanner
        self.selector = selector
        self.timehandler = timehandler
        self.cachehandler = cachehandler
        self.rtinfo = rtinfo
        self.perms = perms

    def getFileNamer(self):
        ""
        return self.namer

    def getTestList(self):
        ""
        return self.tlist

    def prepareTestingDirectory(self):
        ""
        self.locator.createTestingDirectory( self.perms )

    def makeTestList(self, batchid=None):
        ""
        fn = self.namer.getFilePath( batchid )

        self.tlist = TestList.TestList( fn, self.tctor )

        return self.tlist

    def writeCacheFile(self):
        ""
        self.cachehandler.writeCache( self.perms )

    def scanForTests(self):
        ""
        self.scanner.scanPaths( self.tlist )

    def applyPermanentFilters(self):
        ""
        self.selector.applyPermanentFilters( self.tlist )

    def readTestList(self):
        ""
        self.tlist.readTestList()

    def loadTestTimes(self):
        ""
        self.timehandler.load( self.tlist )

    def readAndMergePreviouslyRunTests(self):
        ""
        fn = self.namer.getFilePath()
        prev_tlist = TestList.TestList( fn, self.tctor )

        attrs = prev_tlist.readTestResults()

        fin = prev_tlist.getFinishDate()
        if fin != None:
            attrs['finishepoch'] = fin

        self.tlist.addTestsWithoutOverwrite( prev_tlist.getTests() )
        self.tlist.copyTestResults( prev_tlist.getTests() )

        return attrs

    def writeTestList(self):
        ""
        attrs = self.rtinfo.asDict()
        self.tlist.stringFileWrite( **attrs )
        self.perms.set( self.tlist.getFilename() )

    def addBatchFileLinksToTests(self, batchid):
        ""
        qbat = self.namer.getScriptPath( batchid )
        qout = self.namer.getOutputPath( batchid )

        for tcase in self.tlist.getTests():
            tcase.getSpec().addLinkFile( qbat )
            tcase.getSpec().addLinkFile( qout )

    def prepareActive(self, apply_filters=True, remove_new_skips=False ):
        ""
        self.selector.prepareActiveTests( self.tlist,
                                          apply_filters=apply_filters,
                                          remove_new_skips=remove_new_skips )

    def prepareForBaseline(self):
        ""
        self.selector.prepareBaselineTests( self.tlist )


##############################################################################

def generateTestList( opts, optD, rtdata, tlm ):
    """
    """
    tlist = tlm.makeTestList()

    tlm.prepareTestingDirectory()
    tlm.writeCacheFile()
    tlm.scanForTests()
    tlm.loadTestTimes()
    tlm.applyPermanentFilters()
    tlm.writeTestList()

    rtdata.results_writer.prerun( tlist, rtdata.rtinfo, verbosity=1 )
    print3()

    runner = TestRunner( rtdata.testdir, rtdata.plat, rtdata.rtconfig,
                         rtdata.plugin, rtdata.perms )

    xlist = TestExecList( tlist, runner )
    xlist.createTestExecs()

    print3( "\nTest directory:", basename( rtdata.testdir ) )


def extractTestFiles( scan_type, param_dict, target_dir, rtdata, tlm ):
    """
    Uses all the regular filtering mechanisms to gather tests from a test
    source area and copies the files used for each test into a separate
    directory.
    """
    import libvvtest.extract as extract

    tlist = tlm.makeTestList()

    tlm.scanForTests()
    tlm.readTestList()
    tlm.loadTestTimes()
    tlm.applyPermanentFilters()

    extract.copy_out_test_files( target_dir, tlist.getActiveTests() )


def runTests( opts, optD, rtdata, tlm ):
    """
    Executes a list of tests.
    """
    rtdata.plugin.callPrologue( rtdata.rtinfo.getInfo('cmdline') )

    adjust_filter_settings_for_batch( opts, rtdata.plat, rtdata.rtconfig )

    tlist = tlm.makeTestList()

    check_for_currently_running_vvtest( tlist, opts.force )

    tlm.prepareTestingDirectory()
    tlm.writeCacheFile()

    tlm.scanForTests()
    tlm.readAndMergePreviouslyRunTests()
    tlm.loadTestTimes()
    tlm.applyPermanentFilters()
    tlm.writeTestList()
    tlm.prepareActive()

    tlist.setResultsDate()

    run_test_exec_list( opts, optD, rtdata, rtdata.perms, tlm )

    print3( "Test directory:", basename( rtdata.testdir ) )

    rtdata.plugin.callEpilogue( rtdata.testdir, tlist.getTests() )

    return execute.encode_integer_warning( tlist )


def restartTests( opts, optD, rtdata, tlm ):
    ""
    batchid = opts.qsub_id

    if batchid == None:
        rtdata.plugin.callPrologue( rtdata.rtinfo.getInfo('cmdline') )

    adjust_filter_settings_for_restart( opts, rtdata.rtconfig )

    tlist = tlm.makeTestList( batchid )

    check_for_currently_running_vvtest( tlist, opts.force )

    if batchid == None:
        tlm.readTestList()
        tlm.readAndMergePreviouslyRunTests()
        tlm.loadTestTimes()
        tlm.prepareActive()
        tlist.setResultsDate()
    else:
        tlm.readTestList()
        tlm.addBatchFileLinksToTests( batchid )
        tlm.prepareActive( apply_filters=False )

    run_test_exec_list( opts, optD, rtdata, rtdata.perms, tlm )

    if batchid == None:
        rtdata.plugin.callEpilogue( rtdata.testdir, tlist.getTests() )

    return execute.encode_integer_warning( tlist )


def baselineTests( opts, optD, rtdata, tlm ):
    ""
    tlist = tlm.makeTestList()

    tlm.readAndMergePreviouslyRunTests()

    # if the keyword expression does not include a results keyword, then
    # add the 'diff' keyword so that only diffs are rebaselined by default
    rtdata.rtconfig.addResultsKeywordExpression( 'diff' )

    tlm.prepareForBaseline()

    rtdata.results_writer.prerun( tlist, rtdata.rtinfo, verbosity=1 )
    print3()

    if tlist.numActive() > 0:

        runner = TestRunner( rtdata.testdir, rtdata.plat, rtdata.rtconfig,
                             rtdata.plugin, rtdata.perms )

        xlist = TestExecList( tlist, runner )
        xlist.createTestExecs()

        execute.run_baseline( xlist, rtdata.plat )


def information_output( opts, optD, rtdata, tlm ):
    ""
    exitcode = 0

    if opts.show_times:
        output_timings( opts, optD, rtdata, tlm )
        return exitcode

    tlist = tlm.makeTestList()

    have_cache = ( rtdata.isrestart or os.path.exists( rtdata.testdir ) )

    if not rtdata.isrestart and ( opts.keys or opts.files ):
        tlm.scanForTests()
        tlm.readTestList()
        tlm.loadTestTimes()
        tlm.applyPermanentFilters()

    elif have_cache:
        adjust_filter_settings_for_restart( opts, rtdata.rtconfig )

        tlm.readTestList()
        attrs = tlm.readAndMergePreviouslyRunTests()
        rtdata.rtinfo.setInfo( **attrs )

    else:
        print3( 'WARNING: previous test results directory not found,',
                rtdata.testdir )

    tlm.prepareActive( remove_new_skips=True )

    if opts.keys:
        print_keyword_union( tlist )

    elif opts.files:
        print_test_files( tlist )

    else:
        rtdata.results_writer.info( tlist, rtdata.rtinfo )
        exitcode = execute.encode_integer_warning( tlist )
        rtdata.plugin.callEpilogue( rtdata.testdir, tlist.getTests() )

    return exitcode


def output_timings( opts, optD, rtdata, tlm ):
    ""
    rtdata.plugin.callPrologue( rtdata.rtinfo.getInfo('cmdline') )
    tlist = tlm.makeTestList()

    if not rtdata.isrestart:

        adjust_filter_settings_for_batch( opts, rtdata.plat, rtdata.rtconfig )

        tlm.scanForTests()
        tlm.readAndMergePreviouslyRunTests()
        tlm.loadTestTimes()
        tlm.applyPermanentFilters()
        tlm.prepareActive()

    else:
        adjust_filter_settings_for_restart( opts, rtdata.rtconfig )

        tlm.readAndMergePreviouslyRunTests()
        tlm.loadTestTimes()
        tlm.prepareActive()

    tlist.setResultsDate()

    cwriter = construct_console_writer( rtdata.testdir, opts, optD )
    cwriter.timings( tlist )


def adjust_filter_settings_for_batch( opts, plat, rtconfig ):
    ""
    if opts.batch:
        if opts.dash_N == None and plat.getPluginMaxProcs() == None:
            # we are batching and no num procs limit is available
            rtconfig.applyMaxProcsExpression( False )


def adjust_filter_settings_for_restart( opts, rtconfig ):
    ""
    if opts.dash_N == None:
        # no max procs filter unless -N was given on command line
        rtconfig.applyMaxProcsExpression( False )

    if opts.max_devices == None:
        # no max devices filter unless --max-devices was given on command line
        rtconfig.applyMaxDevicesExpression( False )

    rtconfig.applyTDDExpression( False )


##############################################################################


class CacheFileHandler:

    def __init__(self, opts, optD, rtconfig):
        ""
        self.opts = opts
        self.optD = optD
        self.rtconfig = rtconfig

        self.filename = None

    def setCacheFilename(self, test_dir):
        ""
        self.filename = pjoin( test_dir, 'test.cache' )

    def writeCache(self, perms):
        ""
        with open( self.filename, "w" ) as fp:
            fp.write( 'VERSION=' + str(version) + '\n' )
            if self.opts.plat:
                  fp.write( 'PLATFORM=' + self.opts.plat.strip() + '\n' )
            if self.rtconfig.getAttr('exepath'):
                fp.write( \
                    'PROJECT=' + abspath( self.rtconfig.getAttr('exepath') ) + '\n' )
            if self.optD['onopts']:
                fp.write( 'ONOPTS=' + '+'.join( self.optD['onopts'] ) + '\n' )
            if self.optD['offopts']:
                fp.write( 'OFFOPTS=' + '+'.join( self.optD['offopts'] ) + '\n' )
            if self.opts.dash_T != None:
                fp.write( 'TIMEOUT=' + str(self.opts.dash_T).strip() + '\n' )
            if self.opts.timeout_multiplier != None:
                fp.write( 'TIMEOUT_MULTIPLIER=' + \
                                       str(self.opts.timeout_multiplier).strip() + '\n' )
            if self.opts.dash_e:
                fp.write( 'USE_ENV=1\n' )
            if self.opts.check:
                fp.write( 'CHECK=' + ' '.join( self.opts.check ) + '\n' )
            if self.opts.short_xdirs:
                fp.write( 'SHORT_XDIRS='+self.opts.short_xdirs + '\n' )

        perms.set( abspath(self.filename) )

    def readCache(self):
        ""
        with open( self.filename, "r" ) as fp:
            write_version = 0
            for line in fp.readlines():
                line = line.strip()
                kvpair = line.split( '=', 1 )
                if kvpair[0] == 'VERSION':
                    write_version = kvpair[1]
                elif kvpair[0] == 'PLATFORM':
                    if not self.opts.plat:
                        self.opts.plat = kvpair[1]
                elif kvpair[0] == 'PROJECT':
                    # do not replace if the command line contains -j
                    if not self.opts.bin_dir:
                        self.opts.bin_dir = kvpair[1]
                        self.rtconfig.setAttr( 'exepath', kvpair[1] )
                elif kvpair[0] == 'ONOPTS':
                    self.optD['onopts'] = kvpair[1].split( '+' )
                    self.rtconfig.setAttr( 'onopts', self.optD['onopts'] )
                elif kvpair[0] == 'OFFOPTS':
                    self.optD['offopts'] = kvpair[1].split( '+' )
                    self.rtconfig.setAttr( 'offopts', self.optD['offopts'] )
                elif kvpair[0] == 'TIMEOUT':
                    # do not replace if the command line contains -T
                    if self.opts.dash_T == None:
                        self.opts.dash_T = kvpair[1]
                        self.rtconfig.setAttr( 'timeout', float(self.opts.dash_T) )
                elif kvpair[0] == 'TIMEOUT_MULTIPLIER':
                    if not self.opts.timeout_multiplier:
                        self.opts.timeout_multiplier = float(kvpair[1])
                        self.rtconfig.setAttr( 'multiplier', self.opts.timeout_multiplier )
                elif kvpair[0] == 'USE_ENV':
                    self.opts.dash_e = True
                elif kvpair[0] == 'CHECK':
                    self.opts.check = kvpair[1].split()
                elif kvpair[0] == 'SHORT_XDIRS':
                    if not self.opts.short_xdirs:
                        self.opts.short_xdirs = kvpair[1]


def check_for_currently_running_vvtest( tlist, optforce ):
    ""
    if not optforce and not tlist.resultsFileIsMarkedFinished():
        raise FatalError( 'tests are currently running in another process\n'
            '    (or a previous run was killed); use --force to run anyway' )


def get_output_verbosity_integer( dash_v ):
    ""
    if dash_v:
        verb = dash_v
    else:
        verb = 0

    return verb


def print_keyword_union( tlist ):
    ""
    from libvvtest.teststatus import RESULTS_KEYWORDS

    print3( "\nresults keywords:", ' '.join( RESULTS_KEYWORDS ) )
    kd = {}
    for tcase in tlist.getActiveTests():
        for k in tcase.getSpec().getKeywords( include_implicit=False ):
            kd[k] = None
    L = list( kd.keys() )
    L.sort()
    print3( "\ntest keywords: " )
    while len(L) > 0:
        k1 = L.pop(0)
        if len(L) > 0: k2 = L.pop(0)
        else:          k2 = ''
        if len(L) > 0: k3 = L.pop(0)
        else:          k3 = ''
        print3( "  %-20s %-20s %-20s" % (k1,k2,k3) )


def print_test_files( tlist ):
    ""
    D = {}
    for tcase in tlist.getActiveTests():
        d = normpath( tcase.getSpec().getFilename() )
        D[d] = None
    L = list( D.keys() )
    L.sort()
    for d in L:
        print3( d )


def information_mode( opts ):
    ""
    return opts.dash_i or opts.keys or opts.files


def need_console_output( opts ):
    ""
    if information_mode( opts ):
        if opts.html or opts.junit or opts.gitlab or \
           opts.save_results or opts.cdash:
            return False

    return True


def construct_results_writers( rtdata, opts, optD ):
    ""
    import libvvtest.resultsout as resultsout

    writers = resultsout.ResultsWriters()

    if need_console_output( opts ):
        conobj = construct_console_writer( rtdata.testdir, opts, optD )
        writers.addWriter( conobj )

    if opts.qsub_id == None:

        if opts.html:
            htmlobj = construct_html_writer( rtdata.testdir, opts, optD,
                                             rtdata.perms )
            writers.addWriter( htmlobj )

        if opts.junit:
            junitobj = construct_junit_writer( rtdata.testdir, opts, optD,
                                               rtdata.perms )
            writers.addWriter( junitobj )

        if opts.gitlab:
            wr = construct_gitlab_writer( rtdata.testdir, opts, optD,
                                          rtdata.perms )
            writers.addWriter( wr )

        if opts.cdash:
            wr = construct_cdash_writer( rtdata.testdir, opts, optD,
                                         rtdata.perms )
            writers.addWriter( wr )

        if opts.save_results:
            wr = construct_testlist_writer( rtdata.testdir, opts, optD,
                                            rtdata.perms, rtdata.plat )
            writers.addWriter( wr )

    rtdata.results_writer = writers


def construct_console_writer( test_dir, opts, optD ):
    ""
    import libvvtest.consolewriter as consolewriter

    verb = get_output_verbosity_integer( opts.dash_v )

    conobj = consolewriter.ConsoleWriter( sys.stdout, test_dir, verb )

    conobj.setSortingSpecification( optD['sort_letters'] )

    return conobj


def construct_html_writer( test_dir, opts, optD, perms ):
    ""
    import libvvtest.htmlwriter as htmlwriter

    htmlobj = htmlwriter.HTMLWriter( perms, opts.html, test_dir )

    return htmlobj


def construct_junit_writer( test_dir, opts, optD, perms ):
    ""
    import libvvtest.junitwriter as junitwriter

    junitobj = junitwriter.JUnitWriter( perms, opts.junit, test_dir )

    junitobj.setOutputDate( opts.results_date )

    return junitobj


def construct_gitlab_writer( test_dir, opts, optD, perms ):
    ""
    import libvvtest.gitlabwriter as gitlabwriter

    gitlabobj = gitlabwriter.GitLabWriter( opts.gitlab, test_dir, perms )

    gitlabobj.setSortingSpecification( optD['sort_letters'] )
    gitlabobj.setOutputDate( opts.results_date )
    gitlabobj.setNamingTags( optD['onopts'], opts.results_tag )

    return gitlabobj


def construct_cdash_writer( test_dir, opts, optD, perms ):
    ""
    import libvvtest.cdashwriter as cdashwriter
    import cdashutil

    cdashobj = cdashwriter.CDashWriter( test_dir, perms )

    cdashobj.setCDashFormatter( cdashutil.TestResultsFormatter,
                                cdashutil.FileSubmitter )

    err = cdashobj.initialize( opts.cdash,
                               project=opts.cdash_project,
                               datestamp=opts.results_date,
                               options=optD['onopts'],
                               tag=opts.results_tag )

    if err:
        raise FatalError( err )

    return cdashobj


def construct_testlist_writer( test_dir, opts, optD, perms, platobj ):
    ""
    import libvvtest.listwriter as listwriter

    todir = get_testing_directory( opts, platobj )

    if not listwriter.is_target_like_scp( todir ):
        todir = normpath( abspath( todir ) )

    wlistobj = listwriter.ListWriter( perms, todir, test_dir )

    wlistobj.setOutputDate( opts.results_date )
    wlistobj.setNamingTags( optD['onopts'], opts.results_tag )

    return wlistobj


def get_testing_directory( opts, platobj ):
    ""
    if type( opts.save_results ) == type(''):
        tdir = opts.save_results
    else:
        tdir = platobj.testingDirectory()

    if not tdir:
        raise FatalError( 'failed to determine --save-results directory' )

    return tdir


def run_test_exec_list( opts, optD, rtdata, perms, tlm ):
    ""
    tlist = tlm.getTestList()

    rtdata.results_writer.prerun( tlist, rtdata.rtinfo, verbosity=0 )
    print3()

    if tlist.numActive() > 0:

        # this variable allows vvtest tests to run vvtest (ie, allows recursion)
        os.environ['VVTEST_TEST_ROOT'] = rtdata.testdir

        runner = TestRunner( rtdata.testdir, rtdata.plat, rtdata.rtconfig,
                             rtdata.plugin, perms )

        xlist = TestExecList( tlist, runner )
        xlist.createTestExecs( check_dependencies=(opts.qsub_id == None) )

        tlrun = execute.TestListRunner( rtdata.testdir, tlist, xlist, perms,
                                        rtdata.rtinfo, rtdata.results_writer,
                                        rtdata.plat )

        if not opts.batch:
            tlrun.runDirect( opts.qsub_id )

        else:
            namer = tlm.getFileNamer()
            batch = create_Batcher( opts, optD, rtdata, namer,
                                    tlist, xlist, rtdata.testdir,
                                    rtdata.plat, perms )
            tlrun.runBatch( batch )

    print3()
    rtdata.rtinfo.setInfo( finishepoch=time.time() )
    rtdata.results_writer.postrun( tlist, rtdata.rtinfo )


def create_Batcher( opts, optD, rtdata, namer,
                    tlist, xlist, test_dir, plat, perms ):
    ""
    import libvvtest.batchutils as batchutils
    import batch.batching as batching
    from batch.qinterface import BatchQueueInterface

    assert opts.qsub_id == None

    batchitf = BatchQueueInterface()
    plat.initializeBatchSystem( batchitf )

    qsublimit = opts.batch_limit
    if qsublimit == None:
        qsublimit = plat.getDefaultQsubLimit()

    vvtestcmd = vvtest_command_line_for_batch( opts, optD,
                                               rtdata.exepath,
                                               rtdata.rtconfig )

    check_interval, check_timeout = determine_job_check_intervals()
    jobhandler = batching.BatchJobHandler( check_interval, check_timeout,
                                           batchitf, namer )

    batch = batchutils.Batcher( vvtestcmd,
                                tlist, xlist, perms,
                                qsublimit,
                                opts.batch_length,
                                opts.max_timeout,
                                namer, jobhandler,
                                rtdata.tctor )

    return batch


def determine_job_check_intervals():
    """
    allow these values to be set by environment variable, mainly for
    unit testing; if setting these is needed more regularly then a
    command line option should be added
    """
    check_interval = int( os.environ.get( 'VVTEST_BATCH_CHECK_INTERVAL', 30 ) )
    check_timeout = int( os.environ.get( 'VVTEST_BATCH_CHECK_TIMEOUT', 5*60 ) )

    return check_interval, check_timeout


def vvtest_command_line_for_batch( opts, optD, vvtestpath, rtconfig ):
    ""
    cmd = sys.executable + ' ' + vvtestpath

    if opts.dash_e: cmd += ' -e'
    if opts.dash_m: cmd += ' -m'
    if opts.postclean: cmd += ' -C'
    if opts.analyze: cmd += ' -a'

    cmd += ' -n 1'  # force sequential batch execution

    for cfgdir in rtconfig.getAttr('configdir'):
        cmd += ' --config='+cfgdir

    cmd += ' --plat '+rtconfig.getPlatformName()

    if optD['platopt_dict']:
        for k,v in optD['platopt_dict'].items():
            if v:
                cmd += ' --platopt ' + k + '=' + v
            else:
                cmd += ' --platopt ' + k

    if opts.perms:
        cmd += ' --perms '+','.join( opts.perms )

    for arg in rtconfig.getAttr('testargs'):
        cmd += ' --test-args="'+arg+'"'

    return cmd


###########################################################################

def check_load_bootstrap_file( cwd, exepath ):
    """
    to allow for vvtest to be a soft link to an installed vvtest directory
    tree, look for a bootstrap file in sys.path (which follows soft links)
    then in the directory containing the soft link itself
    """
    bootdir = location.find_sys_directory_with_file( cwd, exepath,
                                                     'vvtest_bootstrap.py' )
    if bootdir:
        try:
            import vvtest_bootstrap
        except ImportError:
            sys.path.append( bootdir )
            import vvtest_bootstrap


def insert_configdirs_into_sys_path( vvtestdir, configdirs ):
    ""
    dL = [ normpath(d) for d in configdirs ]

    d = normpath( pjoin( vvtestdir, 'config' ) )
    if d not in dL:
        dL.append( d )

    dL.reverse()
    for d in dL:
        sys.path.insert( 1, d )


##############################################################################

def print3( *args ):
    ""
    sys.stdout.write( ' '.join( [ str(x) for x in args ] ) + os.linesep )
    sys.stdout.flush()


def get_vvtest_directory():
    ""
    # if vvtest is a soft link, this will follow it
    d = sys.path[0]
    if not d:                  d = os.getcwd()
    elif not os.path.isabs(d): d = abspath(d)
    return d


def adjust_sys_path_for_shared_modules( vvtestdir ):
    ""
    trigdir = normpath( pjoin( vvtestdir, 'trig' ) )

    if os.path.isdir( trigdir ):
        if trigdir not in sys.path:
            sys.path.insert( 1, trigdir )
    else:
        raise FatalError( '*** vvtest error: '
                          'failed to find "trig" directory for imports' )


def main():
    ""
    exepath = normpath( abspath( sys.argv[0] ) )
    vvtestdir = get_vvtest_directory()

    adjust_sys_path_for_shared_modules( vvtestdir )

    try:
        main_entry = MainEntry( sys.argv, vvtestdir, exepath )
        main_entry.constructObjects()

        exitstat = main_entry.execute()
        if exitstat:
            return exitstat

    except FatalError as e:
        sys.stderr.write( '*** vvtest error: '+str(e)+'\n' )
        return 1


if __name__ == '__main__':
    try:
        x = main()
    except KeyboardInterrupt:
        x = 1
    sys.exit(x)
