#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
from os.path import join as pjoin
from os.path import dirname, abspath, normpath, basename
import time
import shlex

import libvvtest.cmdline as cmdline
from libvvtest.execlist import TestExecList
from libvvtest.testrunner import TestRunner
import libvvtest.pathutil as pathutil
from libvvtest.errors import FatalError
import libvvtest.location as location
import libvvtest.execute as execute
from libvvtest.testctor import TestConstructor
import libvvtest.TestList as TestList


version = '1.2'

search_fnmatch = ['*.inp','*.apr','*.i']

USER_PLUGIN_MODULE_NAME = 'vvtest_user_plugin'


class MainEntry:

    def __init__(self, argv, vvtestdir, exepath):
        """
        'vvtestdir' is the (real) directory containing the vvtest script
        """
        self.argv = argv
        self.vvtestdir = vvtestdir
        self.exepath = exepath
        self.curdir = os.getcwd()

        self.loc = Locator( os.getcwd(), self.exepath )

    def constructObjects(self):
        ""
        self.start_epoch = time.time()

        check_load_bootstrap_file( self.loc )

        # this may call sys.exit (for help or errors)
        self.opts, self.optD, self.dirs = \
            cmdline.parse_command_line( self.argv[1:], version )

        if len( self.dirs ) == 0:
            # scan current working directory by default
            self.dirs.append( '.' )

        self.loc.setOptions( mirror=self.opts.dash_M, wipe=self.opts.dash_w )

        configdirs = self.loc.getConfigDirs( self.opts.config )

        insert_configdirs_into_sys_path( self.vvtestdir, configdirs )

        self.constructRuntimeData( configdirs )

        self.constructPlatform()

        tctor = construct_TestConstructor( self.opts )
        self.rtdata.setTestConstructor( tctor )

        self.computeTestDirectory()

        self.rtdata.setPermissionsObject( self.opts, self.optD )

        self.constructResultsWriter()

        self.constructFilteringObjects()

    def execute(self):
        ""
        exitstat = 0

        if information_mode( self.opts ):
            exitstat = information_output( self.opts, self.optD,
                                           self.rtdata, self.tlm )

        elif self.opts.dash_g:
            generateTestList( self.opts, self.optD, self.rtdata, self.tlm )

        elif self.opts.dash_b:

            if self.opts.dash_R or self.opts.dash_w:
                raise FatalError( 'cannot use -R or -w with -b (baseline)' )

            baselineTests( self.opts, self.optD, self.rtdata, self.tlm )

        elif self.opts.extract:
            extractTestFiles( self.opts.scan_type,
                              self.optD['param_dict'],
                              self.opts.extract, self.rtdata, self.tlm )

        else:

            # if no results keywords are specified, then add -k notrun/notdone
            if not self.opts.dash_w and not self.opts.dash_R:
                rtconfig = self.rtdata.getRuntimeConfig()
                rtconfig.addResultsKeywordExpression( 'notrun or notdone' )

            if self.rtdata.isRestartMode():
                exitstat = restartTests( self.opts, self.optD, self.rtdata, self.tlm )
            else:
                exitstat = runTests( self.opts, self.optD, self.rtdata, self.tlm )

        if self.opts.encode_exit_status:
            return exitstat

    def constructRuntimeData(self, configdir):
        ""
        from libvvtest.runinfo import RuntimeInfo

        self.rtdata = RuntimeData( self.exepath )

        rtconfig = construct_RuntimeConfig( self.opts, self.optD )
        self.rtdata.setRuntimeConfig( rtconfig )

        self.cash = CacheFileHandler( self.opts, self.optD, rtconfig )

        # non-None only if the CWD is in a TestResults.* directory
        cache_file = self.loc.findCacheFile()

        if cache_file:
            is_restart = True
            self.cash.setCacheFilename( dirname( cache_file ) )
            self.readCacheData( rtconfig )
        else:
            is_restart = False

        self.rtdata.setRestartMode( is_restart )

        rtinfo = RuntimeInfo( startepoch=self.start_epoch,
                              cmdline=self.argv,
                              vvtestdir=self.vvtestdir,
                              curdir=self.curdir )
        if self.opts.short_xdirs:
            rtinfo.setInfo( shortxdirs=self.opts.short_xdirs )
        self.rtdata.setRuntimeInfo( rtinfo )

        create_configuration( rtconfig, self.opts, self.optD,
                              self.vvtestdir, configdir )

        # this is scheduled for deprecation
        if self.opts.check:
            for n in self.opts.check:
                os.environ[ 'CHECK_' + n.upper() ] = ''

        return rtconfig

    def readCacheData(self, rtconfig):
        ""
        if self.optD['onopts'] or self.optD['offopts'] or self.opts.dash_g:
            raise FatalError( 'the -g, -o, and -O options are not allowed '
                              'in a TestResults directory')

        if self.optD['param_dict']:
            raise FatalError( 'cannot use -S in a TestResults directory' )

        if self.opts.dash_g:
            raise FatalError( 'cannot use -g in a TestResults directory' )

        self.cash.readCache()

    def constructPlatform(self):
        ""
        rtconfig = self.rtdata.getRuntimeConfig()
        rtinfo = self.rtdata.getRuntimeInfo()

        plat = construct_platform_instance( self.vvtestdir, self.opts, self.optD )
        self.rtdata.setPlatformObject( plat )

        rtconfig.setPlatformName( plat.getName() )
        rtconfig.setOptionList( self.optD['onopts'] + [plat.getCompiler()] )
        rtconfig.setMaxSize( plat.getMaxSize() )

        rtinfo.setInfo( platform=plat.getName(),
                        compiler=plat.getCompiler() )

    def computeTestDirectory(self):
        ""
        rtinfo = self.rtdata.getRuntimeInfo()
        plat = self.rtdata.getPlatformObject()

        td = self.loc.setTestingDirectory( self.opts.run_dir,
                                           self.optD['onopts'],
                                           self.optD['offopts'],
                                           plat.getName() )

        self.cash.setCacheFilename( td )
        self.rtdata.setTestResultsDir( td )
        rtinfo.setInfo( rundir=td )

    def constructResultsWriter(self):
        ""
        resw = construct_results_writers( self.opts, self.optD,
                                          self.rtdata.getTestResultsDir(),
                                          self.rtdata.getPermissionsObject(),
                                          self.rtdata.getPlatformObject() )

        self.rtdata.setResultsWriter( resw )

    def constructFilteringObjects(self):
        ""
        from libvvtest.testcreator import TestCreator
        from libvvtest.scanner import TestFileScanner
        from libvvtest.filtering import TestFilter
        from libvvtest.testselector import TestSelector
        from libvvtest.timeout import TimeHandler
        from batch.namer import BatchFileNamer

        rtconfig = self.rtdata.getRuntimeConfig()
        test_dir = self.rtdata.getTestResultsDir()

        creator = TestCreator( rtconfig.getPlatformName(),
                               rtconfig.getOptionList(),
                               self.rtdata.getTestConstructor() )

        scanner = TestFileScanner( creator, self.dirs,
                                   force_params_dict=self.optD['param_dict'],
                                   spectype=self.opts.scan_type )

        plug = import_plugin_module( rtconfig )
        self.rtdata.setUserPlugin( plug )

        testfilter = TestFilter( rtconfig, plug )
        tsel = TestSelector( test_dir, testfilter, creator )

        plat = self.rtdata.getPlatformObject()
        tcache = construct_runtime_lookup_cache( plat )
        timehandler = TimeHandler( plug,
                                   self.opts.dash_T,
                                   self.opts.timeout_multiplier,
                                   self.opts.max_timeout,
                                   tcache )

        namer = BatchFileNamer( test_dir )

        self.tlm = TestListManager( locator=self.loc,
                                    namer=namer,
                                    tctor=self.rtdata.getTestConstructor(),
                                    scanner=scanner,
                                    selector=tsel,
                                    timehandler=timehandler,
                                    cachehandler=self.cash,
                                    perms=self.rtdata.getPermissionsObject() )


def import_plugin_module( rtconfig ):
    ""
    import libvvtest.userplugin as userplugin

    try:
        plugmod = userplugin.import_module_by_name( USER_PLUGIN_MODULE_NAME )

    except userplugin.UserPluginError:
        print3( '*** error in user plugin script:',
                str( sys.exc_info()[1] ).strip() )
        print3( '*** user plugin disabled\n' )
        plugmod = None

    plug = userplugin.UserPluginBridge( rtconfig, plugmod )

    return plug


def create_configuration( rtconfig, opts, optD, vvtestdir, configdirs ):
    ""
    rtconfig.setAttr( 'vvtestdir', vvtestdir )

    if optD['onopts']:
        rtconfig.setAttr( 'onopts', optD['onopts'] )
    if optD['offopts']:
        rtconfig.setAttr( 'offopts', optD['offopts'] )

    if opts.bin_dir:
        rtconfig.setAttr( 'exepath', opts.bin_dir )

    rtconfig.setAttr( 'configdir', configdirs )

    rtconfig.setAttr( 'refresh', not opts.dash_m )
    rtconfig.setAttr( 'postclean', opts.postclean == True )

    if opts.dash_T != None:
        rtconfig.setAttr( 'timeout', opts.dash_T )
    if opts.timeout_multiplier != None:
        rtconfig.setAttr( 'multiplier', opts.timeout_multiplier )

    rtconfig.setAttr( 'preclean', not opts.dash_m )
    rtconfig.setAttr( 'analyze', opts.analyze == True )
    rtconfig.setAttr( 'logfile', not opts.dash_L )

    if opts.test_args:
        argL = []
        for args in opts.test_args:
            argL.extend( shlex.split( args ) )
        rtconfig.setAttr( 'testargs', argL )


class RuntimeData:

    def __init__(self, exepath):
        """
        'exepath' is the absolute path to vvtest (without following soft links)
        """
        self.exepath = exepath

    def getVvtestPath(self): return self.exepath

    def setRuntimeInfo(self, rtinfo): self.rtinfo = rtinfo
    def getRuntimeInfo(self): return self.rtinfo

    def setPlatformObject(self, platobj): self.plat = platobj
    def getPlatformObject(self): return self.plat

    def setRuntimeConfig(self, rtconfig): self.rtconfig = rtconfig
    def getRuntimeConfig(self): return self.rtconfig

    def setUserPlugin(self, plugin): self.plugin = plugin
    def getUserPlugin(self): return self.plugin

    def setTestResultsDir(self, test_dir): self.test_dir = test_dir
    def getTestResultsDir(self): return self.test_dir

    def setRestartMode(self, is_restart): self.is_restart = is_restart
    def isRestartMode(self):
        """
        True if the CWD is within an existing test results directory
        """
        return self.is_restart

    def setPermissionsObject(self, opts, optD):
        self.perms = make_PermissionSetter( self.test_dir, opts.perms )
    def getPermissionsObject(self): return self.perms

    def setResultsWriter(self, writer): self.results_writer = writer
    def getResultsWriter(self): return self.results_writer

    def setTestConstructor(self, tctor): self.tctor = tctor
    def getTestConstructor(self): return self.tctor


def construct_platform_instance( vvtestdir, opts, optD ):
    ""
    import libvvtest.vvplatform as vvplatform

    plat = vvplatform.create_Platform_instance(
                vvtestdir,
                opts.plat, opts.batch,
                optD['platopt_dict'],  # --platopt
                opts.dash_e,
                opts.dash_n,
                opts.dash_N,
                opts.devices,
                opts.max_devices,
                optD['onopts'],        # -o
                optD['offopts'] )      # -O

    return plat


def construct_RuntimeConfig( opts, optD ):
    ""
    from libvvtest.RuntimeConfig import RuntimeConfig

    rtconfig = RuntimeConfig()

    rtconfig.setPlatformExpression( optD['platform_expr'] )
    if opts.dash_A:
        rtconfig.applyPlatformExpression( False )
    rtconfig.setKeywordExpression( optD['keyword_expr'] )
    rtconfig.setParameterExpression( optD['param_list'] )
    rtconfig.setIncludeTDD( opts.include_tdd == True )
    rtconfig.setFileSearch( optD['search_regexes'], search_fnmatch )
    rtconfig.setRuntimeRange( opts.tmin, opts.tmax )
    rtconfig.setRuntimeSum( opts.tsum )

    return rtconfig


def construct_TestConstructor( opts ):
    ""
    tctor = TestConstructor()

    # magic: check and print error if this fails to cast to int
    if opts.short_xdirs:
        tctor.setShorten( int( opts.short_xdirs ) )

    return tctor


class TestListManager:

    def __init__(self, locator, namer, tctor, scanner,
                       selector, timehandler, cachehandler,
                       perms):
        ""
        self.tlist = None

        self.locator = locator
        self.namer = namer
        self.tctor = tctor
        self.scanner = scanner
        self.selector = selector
        self.timehandler = timehandler
        self.cachehandler = cachehandler
        self.perms = perms

    def getFileNamer(self):
        ""
        return self.namer

    def getTestList(self):
        ""
        return self.tlist

    def prepareTestingDirectory(self):
        ""
        self.locator.createTestingDirectory( self.perms )

    def makeTestList(self, batchid=None):
        ""
        fn = self.namer.getFilePath( batchid )

        self.tlist = TestList.TestList( fn, self.tctor )

        return self.tlist

    def writeCacheFile(self):
        ""
        self.cachehandler.writeCache( self.perms )

    def scanForTests(self):
        ""
        self.scanner.scanPaths( self.tlist )

    def applyPermanentFilters(self):
        ""
        self.selector.applyPermanentFilters( self.tlist )

    def readTestList(self):
        ""
        self.tlist.readTestList()

    def loadTestTimes(self):
        ""
        self.timehandler.load( self.tlist )

    def readAndMergePreviouslyRunTests(self):
        ""
        fn = self.namer.getFilePath()
        prev_tlist = TestList.TestList( fn, self.tctor )

        attrs = prev_tlist.readTestResults()

        fin = prev_tlist.getFinishDate()
        if fin != None:
            attrs['finishepoch'] = fin

        self.tlist.addTestsWithoutOverwrite( prev_tlist.getTests() )
        self.tlist.copyTestResults( prev_tlist.getTests() )

        return attrs

    def addBatchFileLinksToTests(self, batchid):
        ""
        qbat = self.namer.getScriptPath( batchid )
        qout = self.namer.getOutputPath( batchid )

        for tcase in self.tlist.getTests():
            tcase.getSpec().addLinkFile( qbat )
            tcase.getSpec().addLinkFile( qout )

    def prepareActive(self, apply_filters=True, remove_new_skips=False ):
        ""
        self.selector.prepareActiveTests( self.tlist,
                                          apply_filters=apply_filters,
                                          remove_new_skips=remove_new_skips )

    def prepareForBaseline(self):
        ""
        self.selector.prepareBaselineTests( self.tlist )


def write_test_list_file( tlist, file_attrs, perms ):
    ""
    tlist.stringFileWrite( **file_attrs )
    perms.set( tlist.getFilename() )


##############################################################################

def generateTestList( opts, optD, rtdata, tlm ):
    """
    """
    rtconfig = rtdata.getRuntimeConfig()
    plat = rtdata.getPlatformObject()
    test_dir = rtdata.getTestResultsDir()
    perms = rtdata.getPermissionsObject()
    plugin = rtdata.getUserPlugin()
    rtinfo = rtdata.getRuntimeInfo()

    tlist = tlm.makeTestList()

    tlm.prepareTestingDirectory()
    tlm.writeCacheFile()

    tlm.scanForTests()
    tlm.loadTestTimes()
    tlm.applyPermanentFilters()

    write_test_list_file( tlist, rtinfo.asDict(), perms )

    rtdata.getResultsWriter().prerun( tlist, rtinfo, verbosity=1 )
    print3()

    runner = TestRunner( test_dir, plat, rtconfig, plugin, perms )

    xlist = TestExecList( tlist, runner )
    xlist.createTestExecs()

    print3( "\nTest directory:", basename( test_dir ) )


def extractTestFiles( scan_type, param_dict, target_dir, rtdata, tlm ):
    """
    Uses all the regular filtering mechanisms to gather tests from a test
    source area and copies the files used for each test into a separate
    directory.
    """
    import libvvtest.extract as extract

    tlist = tlm.makeTestList()

    tlm.scanForTests()
    tlm.readTestList()
    tlm.loadTestTimes()
    tlm.applyPermanentFilters()

    extract.copy_out_test_files( target_dir, tlist.getActiveTests() )


def runTests( opts, optD, rtdata, tlm ):
    """
    Executes a list of tests.
    """
    plat = rtdata.getPlatformObject()
    test_dir = rtdata.getTestResultsDir()
    rtinfo = rtdata.getRuntimeInfo()
    perms = rtdata.getPermissionsObject()
    rtconfig = rtdata.getRuntimeConfig()

    rtdata.getUserPlugin().callPrologue( rtinfo.getInfo('cmdline') )

    adjust_filter_settings_for_batch( opts, plat, rtconfig )

    tlist = tlm.makeTestList()

    check_for_currently_running_vvtest( tlist, opts.force )

    tlm.prepareTestingDirectory()
    tlm.writeCacheFile()

    tlm.scanForTests()
    tlm.readAndMergePreviouslyRunTests()
    tlm.loadTestTimes()
    tlm.applyPermanentFilters()

    write_test_list_file( tlist, rtinfo.asDict(), perms )
    tlm.prepareActive()

    tlist.setResultsDate()

    run_test_exec_list( opts, optD, rtdata, perms, tlm )

    print3( "Test directory:", basename( test_dir ) )

    call_user_epilogue( rtdata, tlist )

    return execute.encode_integer_warning( tlist )


def restartTests( opts, optD, rtdata, tlm ):
    ""
    batchid = opts.qsub_id
    plat = rtdata.getPlatformObject()
    test_dir = rtdata.getTestResultsDir()
    rtconfig = rtdata.getRuntimeConfig()
    rtinfo = rtdata.getRuntimeInfo()
    perms = rtdata.getPermissionsObject()

    if batchid == None:
        rtdata.getUserPlugin().callPrologue( rtinfo.getInfo('cmdline') )

    adjust_filter_settings_for_restart( opts, rtconfig )

    tlist = tlm.makeTestList( batchid )

    check_for_currently_running_vvtest( tlist, opts.force )

    if batchid == None:
        tlm.readTestList()
        tlm.readAndMergePreviouslyRunTests()
        tlm.loadTestTimes()
        tlm.prepareActive()
        tlist.setResultsDate()
    else:
        tlm.readTestList()
        tlm.addBatchFileLinksToTests( batchid )
        tlm.prepareActive( apply_filters=False )

    run_test_exec_list( opts, optD, rtdata, perms, tlm )

    if batchid == None:
        call_user_epilogue( rtdata, tlist )

    return execute.encode_integer_warning( tlist )


def baselineTests( opts, optD, rtdata, tlm ):
    ""
    rtconfig = rtdata.getRuntimeConfig()
    plat = rtdata.getPlatformObject()
    test_dir = rtdata.getTestResultsDir()
    plugin = rtdata.getUserPlugin()
    rtinfo = rtdata.getRuntimeInfo()

    tlist = tlm.makeTestList()

    tlm.readAndMergePreviouslyRunTests()

    # if the keyword expression does not include a results keyword, then
    # add the 'diff' keyword so that only diffs are rebaselined by default
    rtconfig.addResultsKeywordExpression( 'diff' )

    tlm.prepareForBaseline()

    rtdata.getResultsWriter().prerun( tlist, rtinfo, verbosity=1 )
    print3()

    if tlist.numActive() > 0:

        perms = rtdata.getPermissionsObject()
        runner = TestRunner( test_dir, plat, rtconfig, plugin, perms )

        xlist = TestExecList( tlist, runner )
        xlist.createTestExecs()

        execute.run_baseline( xlist, plat )


def information_output( opts, optD, rtdata, tlm ):
    ""
    exitcode = 0

    if opts.show_times:
        output_timings( opts, optD, rtdata, tlm )
        return exitcode

    test_dir = rtdata.getTestResultsDir()
    rtconfig = rtdata.getRuntimeConfig()
    rtinfo = rtdata.getRuntimeInfo()
    plat = rtdata.getPlatformObject()

    tlist = tlm.makeTestList()

    restart = rtdata.isRestartMode()
    have_cache = ( restart or os.path.exists( test_dir ) )

    if not restart and ( opts.keys or opts.files ):
        tlm.scanForTests()
        tlm.readTestList()
        tlm.loadTestTimes()
        tlm.applyPermanentFilters()

    elif have_cache:
        adjust_filter_settings_for_restart( opts, rtconfig )

        tlm.readTestList()
        attrs = tlm.readAndMergePreviouslyRunTests()
        rtinfo.setInfo( **attrs )

    else:
        print3( 'WARNING: previous test results directory not found,', test_dir )

    tlm.prepareActive( remove_new_skips=True )

    if opts.keys:
        print_keyword_union( tlist )

    elif opts.files:
        print_test_files( tlist )

    else:
        rtinfo = rtdata.getRuntimeInfo()
        rtdata.getResultsWriter().info( tlist, rtinfo )
        exitcode = execute.encode_integer_warning( tlist )
        call_user_epilogue( rtdata, tlist )

    return exitcode


def output_timings( opts, optD, rtdata, tlm ):
    ""
    plat = rtdata.getPlatformObject()
    rtinfo = rtdata.getRuntimeInfo()
    rtconfig = rtdata.getRuntimeConfig()
    results_writer = rtdata.getResultsWriter()
    test_dir = rtdata.getTestResultsDir()

    rtdata.getUserPlugin().callPrologue( rtinfo.getInfo('cmdline') )
    tlist = tlm.makeTestList()

    if not rtdata.isRestartMode():

        adjust_filter_settings_for_batch( opts, plat, rtconfig )

        tlm.scanForTests()
        tlm.readAndMergePreviouslyRunTests()
        tlm.loadTestTimes()
        tlm.applyPermanentFilters()
        tlm.prepareActive()

    else:
        adjust_filter_settings_for_restart( opts, rtconfig )

        tlm.readAndMergePreviouslyRunTests()
        tlm.loadTestTimes()
        tlm.prepareActive()

    tlist.setResultsDate()

    cwriter = construct_console_writer( test_dir, opts, optD )
    cwriter.timings( tlist )


def adjust_filter_settings_for_batch( opts, plat, rtconfig ):
    ""
    if opts.batch:
        if opts.dash_N == None and plat.getPluginMaxProcs() == None:
            # we are batching and no num procs limit is available
            rtconfig.applyMaxProcsExpression( False )


def adjust_filter_settings_for_restart( opts, rtconfig ):
    ""
    if opts.dash_N == None:
        # no max procs filter unless -N was given on command line
        rtconfig.applyMaxProcsExpression( False )

    if opts.max_devices == None:
        # no max devices filter unless --max-devices was given on command line
        rtconfig.applyMaxDevicesExpression( False )

    rtconfig.applyTDDExpression( False )


##############################################################################


def construct_runtime_lookup_cache( plat ):
    ""
    from libvvtest.fmtresults import LookupCache

    pname = plat.getName()
    cplr = plat.getCompiler()
    tdir = plat.testingDirectory()

    cache = LookupCache( pname, cplr, tdir )

    return cache


class Locator:

    def __init__(self, curdir, exepath):
        ""
        self.curdir = curdir
        self.exepath = exepath

        self.mirror = None
        self.wipe = False

        self.cashfile = None
        self.testdir = None

    def setOptions(self, mirror=None, wipe=None):
        ""
        if mirror != None:
            self.mirror = mirror
        if wipe != None:
            self.wipe = wipe

    def findDirectoryWithBootstrapFile(self):
        """
        to allow for vvtest to be a soft link to an installed vvtest directory
        tree, look for a bootstrap file in sys.path (which follows soft links)
        then in the directory containing the soft link itself
        """
        for dn in sys.path + [dirname(self.exepath)]:
            fn = self.makeAbsPath( pjoin( dn, 'vvtest_bootstrap.py' ) )
            if os.path.exists( fn ):
                return dirname( normpath(fn) )

        return None

    def getConfigDirs(self, cmdline_configdir=None):
        ""
        varval = os.getenv( 'VVTEST_CONFIGDIR' )
        cdir = location.collect_config_dirs( cmdline_configdir, varval )
        return cdir

    def findCacheFile(self):
        """
        returns None if the CWD is not inside a TestResults directory
        """
        # an environment variable is used to identify vvtest run recursion
        troot = os.environ.get( 'VVTEST_TEST_ROOT', None )

        self.cashfile = location.find_vvtest_test_root_file( self.curdir,
                                                             troot,
                                                             'test.cache' )

        return self.cashfile

    def setTestingDirectory(self, rundir, onopts, offopts, platname):
        ""
        sd = location.test_results_subdir_name( rundir,
                                                onopts, offopts,
                                                platname )

        if self.cashfile:
            assert os.path.isabs( self.cashfile )
            self.testdir = normpath( dirname( self.cashfile ) )
        else:
            self.testdir = self.makeAbsPath( sd )

        return self.testdir

    def createTestingDirectory(self, perms):
        ""
        location.create_test_directory( self.testdir, self.mirror,
                                        self.curdir, perms )

        if self.wipe:
            pathutil.remove_directory_contents( self.testdir )

    def makeAbsPath(self, path):
        ""
        if os.path.isabs( path ):
            return path
        else:
            return pjoin( self.curdir, path )


class CacheFileHandler:

    def __init__(self, opts, optD, rtconfig):
        ""
        self.opts = opts
        self.optD = optD
        self.rtconfig = rtconfig

        self.filename = None

    def setCacheFilename(self, test_dir):
        ""
        self.filename = pjoin( test_dir, 'test.cache' )

    def writeCache(self, perms):
        ""
        with open( self.filename, "w" ) as fp:
            fp.write( 'VERSION=' + str(version) + '\n' )
            if self.opts.plat:
                  fp.write( 'PLATFORM=' + self.opts.plat.strip() + '\n' )
            if self.rtconfig.getAttr('exepath'):
                fp.write( \
                    'PROJECT=' + abspath( self.rtconfig.getAttr('exepath') ) + '\n' )
            if self.optD['onopts']:
                fp.write( 'ONOPTS=' + '+'.join( self.optD['onopts'] ) + '\n' )
            if self.optD['offopts']:
                fp.write( 'OFFOPTS=' + '+'.join( self.optD['offopts'] ) + '\n' )
            if self.opts.dash_T != None:
                fp.write( 'TIMEOUT=' + str(self.opts.dash_T).strip() + '\n' )
            if self.opts.timeout_multiplier != None:
                fp.write( 'TIMEOUT_MULTIPLIER=' + \
                                       str(self.opts.timeout_multiplier).strip() + '\n' )
            if self.opts.dash_e:
                fp.write( 'USE_ENV=1\n' )
            if self.opts.check:
                fp.write( 'CHECK=' + ' '.join( self.opts.check ) + '\n' )
            if self.opts.short_xdirs:
                fp.write( 'SHORT_XDIRS='+self.opts.short_xdirs + '\n' )

        perms.set( abspath(self.filename) )

    def readCache(self):
        ""
        with open( self.filename, "r" ) as fp:
            write_version = 0
            for line in fp.readlines():
                line = line.strip()
                kvpair = line.split( '=', 1 )
                if kvpair[0] == 'VERSION':
                    write_version = kvpair[1]
                elif kvpair[0] == 'PLATFORM':
                    if not self.opts.plat:
                        self.opts.plat = kvpair[1]
                elif kvpair[0] == 'PROJECT':
                    # do not replace if the command line contains -j
                    if not self.opts.bin_dir:
                        self.opts.bin_dir = kvpair[1]
                        self.rtconfig.setAttr( 'exepath', kvpair[1] )
                elif kvpair[0] == 'ONOPTS':
                    self.optD['onopts'] = kvpair[1].split( '+' )
                    self.rtconfig.setAttr( 'onopts', self.optD['onopts'] )
                elif kvpair[0] == 'OFFOPTS':
                    self.optD['offopts'] = kvpair[1].split( '+' )
                    self.rtconfig.setAttr( 'offopts', self.optD['offopts'] )
                elif kvpair[0] == 'TIMEOUT':
                    # do not replace if the command line contains -T
                    if self.opts.dash_T == None:
                        self.opts.dash_T = kvpair[1]
                        self.rtconfig.setAttr( 'timeout', float(self.opts.dash_T) )
                elif kvpair[0] == 'TIMEOUT_MULTIPLIER':
                    if not self.opts.timeout_multiplier:
                        self.opts.timeout_multiplier = float(kvpair[1])
                        self.rtconfig.setAttr( 'multiplier', self.opts.timeout_multiplier )
                elif kvpair[0] == 'USE_ENV':
                    self.opts.dash_e = True
                elif kvpair[0] == 'CHECK':
                    self.opts.check = kvpair[1].split()
                elif kvpair[0] == 'SHORT_XDIRS':
                    if not self.opts.short_xdirs:
                        self.opts.short_xdirs = kvpair[1]


def call_user_epilogue( rtdata, tlist ):
    ""
    rdir = rtdata.getTestResultsDir()
    plug = rtdata.getUserPlugin()
    plug.callEpilogue( rdir, tlist.getTests() )


def check_for_currently_running_vvtest( tlist, optforce ):
    ""
    if not optforce and not tlist.resultsFileIsMarkedFinished():
        raise FatalError( 'tests are currently running in another process\n'
            '    (or a previous run was killed); use --force to run anyway' )


def get_output_verbosity_integer( dash_v ):
    ""
    if dash_v:
        verb = dash_v
    else:
        verb = 0

    return verb


def print_keyword_union( tlist ):
    ""
    from libvvtest.teststatus import RESULTS_KEYWORDS

    print3( "\nresults keywords:", ' '.join( RESULTS_KEYWORDS ) )
    kd = {}
    for tcase in tlist.getActiveTests():
        for k in tcase.getSpec().getKeywords( include_implicit=False ):
            kd[k] = None
    L = list( kd.keys() )
    L.sort()
    print3( "\ntest keywords: " )
    while len(L) > 0:
        k1 = L.pop(0)
        if len(L) > 0: k2 = L.pop(0)
        else:          k2 = ''
        if len(L) > 0: k3 = L.pop(0)
        else:          k3 = ''
        print3( "  %-20s %-20s %-20s" % (k1,k2,k3) )


def print_test_files( tlist ):
    ""
    D = {}
    for tcase in tlist.getActiveTests():
        d = normpath( tcase.getSpec().getFilename() )
        D[d] = None
    L = list( D.keys() )
    L.sort()
    for d in L:
        print3( d )


def information_mode( opts ):
    ""
    return opts.dash_i or opts.keys or opts.files


def need_console_output( opts ):
    ""
    if information_mode( opts ):
        if opts.html or opts.junit or opts.gitlab or \
           opts.save_results or opts.cdash:
            return False

    return True


def construct_results_writers( opts, optD, test_dir, perms, platobj ):
    ""
    import libvvtest.resultsout as resultsout

    writers = resultsout.ResultsWriters()

    if need_console_output( opts ):
        conobj = construct_console_writer( test_dir, opts, optD )
        writers.addWriter( conobj )

    if opts.qsub_id == None:

        if opts.html:
            htmlobj = construct_html_writer( test_dir, opts, optD, perms )
            writers.addWriter( htmlobj )

        if opts.junit:
            junitobj = construct_junit_writer( test_dir, opts, optD, perms )
            writers.addWriter( junitobj )

        if opts.gitlab:
            wr = construct_gitlab_writer( test_dir, opts, optD, perms )
            writers.addWriter( wr )

        if opts.cdash:
            wr = construct_cdash_writer( test_dir, opts, optD, perms )
            writers.addWriter( wr )

        if opts.save_results:
            wr = construct_testlist_writer( test_dir, opts, optD, perms, platobj )
            writers.addWriter( wr )

    return writers


def construct_console_writer( test_dir, opts, optD ):
    ""
    import libvvtest.consolewriter as consolewriter

    verb = get_output_verbosity_integer( opts.dash_v )

    conobj = consolewriter.ConsoleWriter( sys.stdout, test_dir, verb )

    conobj.setSortingSpecification( optD['sort_letters'] )

    return conobj


def construct_html_writer( test_dir, opts, optD, perms ):
    ""
    import libvvtest.htmlwriter as htmlwriter

    htmlobj = htmlwriter.HTMLWriter( perms, opts.html, test_dir )

    return htmlobj


def construct_junit_writer( test_dir, opts, optD, perms ):
    ""
    import libvvtest.junitwriter as junitwriter

    junitobj = junitwriter.JUnitWriter( perms, opts.junit, test_dir )

    junitobj.setOutputDate( opts.results_date )

    return junitobj


def construct_gitlab_writer( test_dir, opts, optD, perms ):
    ""
    import libvvtest.gitlabwriter as gitlabwriter

    gitlabobj = gitlabwriter.GitLabWriter( opts.gitlab, test_dir, perms )

    gitlabobj.setSortingSpecification( optD['sort_letters'] )
    gitlabobj.setOutputDate( opts.results_date )
    gitlabobj.setNamingTags( optD['onopts'], opts.results_tag )

    return gitlabobj


def construct_cdash_writer( test_dir, opts, optD, perms ):
    ""
    import libvvtest.cdashwriter as cdashwriter
    import cdashutil

    cdashobj = cdashwriter.CDashWriter( test_dir, perms )

    cdashobj.setCDashFormatter( cdashutil.TestResultsFormatter,
                                cdashutil.FileSubmitter )

    err = cdashobj.initialize( opts.cdash,
                               project=opts.cdash_project,
                               datestamp=opts.results_date,
                               options=optD['onopts'],
                               tag=opts.results_tag )

    if err:
        raise FatalError( err )

    return cdashobj


def construct_testlist_writer( test_dir, opts, optD, perms, platobj ):
    ""
    import libvvtest.listwriter as listwriter

    todir = get_testing_directory( opts, platobj )

    if not listwriter.is_target_like_scp( todir ):
        todir = normpath( abspath( todir ) )

    wlistobj = listwriter.ListWriter( perms, todir, test_dir )

    wlistobj.setOutputDate( opts.results_date )
    wlistobj.setNamingTags( optD['onopts'], opts.results_tag )

    return wlistobj


def get_testing_directory( opts, platobj ):
    ""
    if type( opts.save_results ) == type(''):
        tdir = opts.save_results
    else:
        tdir = platobj.testingDirectory()

    if not tdir:
        raise FatalError( 'failed to determine --save-results directory' )

    return tdir


def run_test_exec_list( opts, optD, rtdata, perms, tlm ):
    ""
    rtconfig = rtdata.getRuntimeConfig()
    plat = rtdata.getPlatformObject()
    plugin = rtdata.getUserPlugin()
    rtinfo = rtdata.getRuntimeInfo()
    results_writer = rtdata.getResultsWriter()
    test_dir = rtdata.getTestResultsDir()
    tlist = tlm.getTestList()

    results_writer.prerun( tlist, rtinfo, verbosity=0 )
    print3()

    if tlist.numActive() > 0:

        # this variable allows vvtest tests to run vvtest (ie, allows recursion)
        os.environ['VVTEST_TEST_ROOT'] = test_dir

        runner = TestRunner( test_dir, plat, rtconfig, plugin, perms )

        xlist = TestExecList( tlist, runner )
        xlist.createTestExecs( check_dependencies=(opts.qsub_id == None) )

        tlrun = execute.TestListRunner( test_dir, tlist, xlist, perms,
                                        rtinfo, results_writer, plat )

        if not opts.batch:
            tlrun.runDirect( opts.qsub_id )

        else:
            namer = tlm.getFileNamer()
            batch = create_Batcher( opts, optD, rtdata, namer,
                                    tlist, xlist, test_dir, plat, perms )
            tlrun.runBatch( batch )

    print3()
    rtinfo.setInfo( finishepoch=time.time() )
    results_writer.postrun( tlist, rtinfo )


def create_Batcher( opts, optD, rtdata, namer,
                    tlist, xlist, test_dir, plat, perms ):
    ""
    import libvvtest.batchutils as batchutils
    import batch.batching as batching
    from batch.qinterface import BatchQueueInterface

    assert opts.qsub_id == None

    batchitf = BatchQueueInterface()
    plat.initializeBatchSystem( batchitf )

    qsublimit = opts.batch_limit
    if qsublimit == None:
        qsublimit = plat.getDefaultQsubLimit()

    vvtestcmd = vvtest_command_line_for_batch( opts, optD,
                                               rtdata.getVvtestPath(),
                                               rtdata.getRuntimeConfig() )

    check_interval, check_timeout = determine_job_check_intervals()
    jobhandler = batching.BatchJobHandler( check_interval, check_timeout,
                                           batchitf, namer )

    tctor = rtdata.getTestConstructor()

    batch = batchutils.Batcher( vvtestcmd,
                                tlist, xlist, perms,
                                qsublimit,
                                opts.batch_length,
                                opts.max_timeout,
                                namer, jobhandler,
                                tctor )

    return batch


def determine_job_check_intervals():
    """
    allow these values to be set by environment variable, mainly for
    unit testing; if setting these is needed more regularly then a
    command line option should be added
    """
    check_interval = int( os.environ.get( 'VVTEST_BATCH_CHECK_INTERVAL', 30 ) )
    check_timeout = int( os.environ.get( 'VVTEST_BATCH_CHECK_TIMEOUT', 5*60 ) )

    return check_interval, check_timeout


def vvtest_command_line_for_batch( opts, optD, vvtestpath, rtconfig ):
    ""
    cmd = sys.executable + ' ' + vvtestpath

    if opts.dash_e: cmd += ' -e'
    if opts.dash_m: cmd += ' -m'
    if opts.postclean: cmd += ' -C'
    if opts.analyze: cmd += ' -a'

    cmd += ' -n 1'  # force sequential batch execution

    for cfgdir in rtconfig.getAttr('configdir'):
        cmd += ' --config='+cfgdir

    cmd += ' --plat '+rtconfig.getPlatformName()

    if optD['platopt_dict']:
        for k,v in optD['platopt_dict'].items():
            if v:
                cmd += ' --platopt ' + k + '=' + v
            else:
                cmd += ' --platopt ' + k

    if opts.perms:
        cmd += ' --perms '+','.join( opts.perms )

    for arg in rtconfig.getAttr('testargs'):
        cmd += ' --test-args="'+arg+'"'

    return cmd


###########################################################################

def check_load_bootstrap_file( locator ):
    ""
    bootdir = locator.findDirectoryWithBootstrapFile()
    if bootdir:
        try:
            import vvtest_bootstrap
        except ImportError:
            sys.path.append( bootdir )
            import vvtest_bootstrap


def insert_configdirs_into_sys_path( vvtestdir, configdirs ):
    ""
    dL = [ normpath(d) for d in configdirs ]

    d = normpath( pjoin( vvtestdir, 'config' ) )
    if d not in dL:
        dL.append( d )

    dL.reverse()
    for d in dL:
        sys.path.insert( 1, d )


def make_PermissionSetter( test_dir, optperms ):
    ""
    if optperms:
        from libvvtest.permsetter import PermissionSetter
        perms = PermissionSetter( test_dir, optperms )

    else:
        class DummyPermissionSetter:
            def __init__(self): pass
            def set(self, path): pass
            def recurse(self, path): pass

        perms = DummyPermissionSetter()

    return perms


##############################################################################

def print3( *args ):
    ""
    sys.stdout.write( ' '.join( [ str(x) for x in args ] ) + os.linesep )
    sys.stdout.flush()


def get_vvtest_directory():
    ""
    # if vvtest is a soft link, this will follow it
    d = sys.path[0]
    if not d:                  d = os.getcwd()
    elif not os.path.isabs(d): d = abspath(d)
    return d


def adjust_sys_path_for_shared_modules( vvtestdir ):
    ""
    trigdir = normpath( pjoin( vvtestdir, 'trig' ) )

    if os.path.isdir( trigdir ):
        if trigdir not in sys.path:
            sys.path.insert( 1, trigdir )
    else:
        raise FatalError( '*** vvtest error: '
                          'failed to find "trig" directory for imports' )


def main():
    ""
    exepath = normpath( abspath( sys.argv[0] ) )
    vvtestdir = get_vvtest_directory()

    adjust_sys_path_for_shared_modules( vvtestdir )

    try:
        main_entry = MainEntry( sys.argv, vvtestdir, exepath )
        main_entry.constructObjects()

        exitstat = main_entry.execute()
        if exitstat:
            return exitstat

    except FatalError as e:
        sys.stderr.write( '*** vvtest error: '+str(e)+'\n' )
        return 1


if __name__ == '__main__':
    try:
        x = main()
    except KeyboardInterrupt:
        x = 1
    sys.exit(x)
