#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST: vvtest

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
from os.path import join as pjoin
from os.path import abspath
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3

install_script = sys.executable + ' ' + pjoin( vtu.topdir, 'install_vvtest' )


class the_tests( vtu.vvtestTestCase ):

    def test_get_help_from_the_install_script(self):
        ""
        x,out = util.runcmd( install_script+' -h' )
        assert x == 0
        assert 'OPTIONS' in out

        x,out = util.runcmd( install_script+' --help' )
        assert x == 0
        assert 'OPTIONS' in out

    def test_install_vvtest_locally_and_run_it(self):
        ""
        loc = abspath( 'vvinst' )
        vvcmd = pjoin( loc, 'vvtest' )

        x,out = util.runcmd( install_script+' '+loc )
        assert x == 0

        util.writefile( 'subdir/mytest.vvt', """
            #VVT: parameterize : np = 1 2
            import vvtest_util
            import script_util
            """ )
        time.sleep(1)

        for batch in [False,True]:
            with util.change_directory( 'subdir' ):

                vtu.remove_results()

                cmd = vtu.vvtest_command_line( '--perms o=',
                                               vvtestpath=vvcmd, batch=batch )
                x,out = util.runcmd( cmd )

                assert x == 0
                cntD = vtu.parse_vvtest_counts( out )
                assert cntD['total'] == 2 and cntD['npass'] == 2

    def test_results_plugin_is_used_if_given(self):
        ""
        util.writefile( 'config/results_plugin.py',
            'print ( "hello from plugin" )' )
        time.sleep(1)

        x,out = util.runcmd( vtu.resultspy+' report' )
        assert x == 0
        assert 'hello from plugin' not in out

        cmd = vtu.resultspy+' report --config '+abspath('config')
        x,out = util.runcmd( cmd )
        assert x == 0
        assert 'hello from plugin' in out

        with util.set_environ( VVTEST_CONFIGDIR=abspath('config') ):
            x,out = util.runcmd( vtu.resultspy+' report' )
            assert x == 0
            assert 'hello from plugin' in out

        os.symlink( vtu.resultspy, 'results.py' )
        time.sleep(1)

        cmd = sys.executable + ' results.py report --config '+abspath('config')
        x,out = util.runcmd( cmd )
        assert x == 0
        assert 'hello from plugin' in out

        x,out = util.runcmd( sys.executable + ' results.py report' )
        assert x == 0
        assert 'hello from plugin' in out


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
