#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST: vvtest

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import platform
from os.path import abspath
from os.path import join as pjoin
import time

import vvtestutils as vtu
import testutils as util
from vvtestutils import clean_sys_path_and_plugin_modules

import libvvtest.makeplatform as makeplatform
from libvvtest.makeplatform import determine_platform_and_compiler


class idplatform( vtu.vvtestTestCase ):

    def test_cleaning_sys_path_and_plugin_modules_for_unit_testing(self):
        ""
        util.writefile( 'adir/idplatform.py', 'pass' )
        adir = abspath( 'adir' )

        savepath = list( sys.path )
        try:
            sys.path.insert( 0, adir )
            sys.path.append( adir )
            assert adir in sys.path
            clean_sys_path_and_plugin_modules()
            assert adir not in sys.path
        finally:
            sys.path[:] = savepath

    def test_import_idplatform_module(self):
        ""
        util.writefile( 'adir/idplatform.py', """
            def hello():
                return 'world'
            """ )
        adir = abspath( 'adir' )
        time.sleep(1)

        # None is returned if idplatform.py not in sys.path
        with vtu.clean_sys_path():
            assert makeplatform.import_plugin_file( 'idplatform.py' ) is None

        # module returned if idplatform.py is in sys.path
        with vtu.clean_sys_path():
            sys.path.insert( 0, adir )
            idp = makeplatform.import_plugin_file( 'idplatform.py' )
            assert idp.hello() == 'world'

    def test_using_idplatform_to_define_platform_and_compiler(self):
        ""
        util.writefile( 'adir/idplatform.py', """
            def platform( opts ):
                return 'XBox'
            def compiler( platname, opts ):
                return 'llvm'
            """ )
        adir = abspath( 'adir' )
        time.sleep(1)

        with vtu.clean_sys_path():
            plat1,cplr1 = determine_platform_and_compiler( None, [], [] )
            plat2,cplr2 = determine_platform_and_compiler( 'foo', [], [] )
            assert plat1 == platform.uname()[0] and cplr1 is None
            assert plat2 == 'foo' and cplr2 is None

        with vtu.clean_sys_path():
            sys.path.insert( 0, adir )
            plat1,cplr1 = determine_platform_and_compiler( None, [], [] )
            plat2,cplr2 = determine_platform_and_compiler( 'foo', [], [] )
            assert plat1 == 'XBox' and cplr1 == 'llvm'
            assert plat2 == 'foo' and cplr2 == 'llvm'


class construction( vtu.vvtestTestCase ):

    def test_parsing_attributes(self):
        ""
        psr = makeplatform.AttrParser( [['foo',str,'desc']] )
        attrs = psr.parse_in_place( {} )
        self.assertEqual( attrs, {} )
        attrs = psr.parse_in_place( {'foo':'fooval'} )
        self.assertEqual( attrs, {'foo':'fooval'} )

        psr = makeplatform.AttrParser( [['foo',int,'desc']] )
        attrs = psr.parse_in_place( {'foo':'3'} )
        self.assertEqual( attrs, {'foo':3} )
        attrs = psr.parse_in_place( {'foo':3} )
        self.assertEqual( attrs, {'foo':3} )
        self.assertRaises( Exception, psr.parse_in_place, {'foo':'bar'} )

        psr = makeplatform.AttrParser( [['foo',int,'bar','desc']] )
        attrs = psr.parse_in_place( {'foo':3} )
        self.assertEqual( attrs, {'foo':3} )
        attrs = psr.parse_in_place( {'bar':3} )
        self.assertEqual( attrs, {'foo':3} )
        attrs = psr.parse_in_place( {'bar':3, 'foo':'3'} )
        self.assertEqual( attrs, {'foo':3} )
        self.assertRaises( Exception, psr.parse_in_place, {'bar':'3', 'foo':'4'} )

        psr = makeplatform.AttrParser( [['foo',int,'bar','baz','desc']] )
        self.assertEqual( psr.parse_in_place( {'foo':3} ), {'foo':3} )
        self.assertEqual( psr.parse_in_place( {'bar':3} ), {'foo':3} )
        self.assertEqual( psr.parse_in_place( {'baz':3} ), {'foo':3} )

        psr = makeplatform.AttrParser( [['foo',str,'desc1'],
                                        ['bar',int,'baz','desc2']] )
        self.assertEqual( psr.parse_in_place( {'foo':'a'} ), {'foo':'a'} )
        self.assertEqual( psr.parse_in_place( {'baz':2} ), {'bar':2} )
        attrs = psr.parse_in_place( {'baz':2,'foo':'b'} )
        self.assertEqual( attrs, {'foo':'b', 'bar':2} )

        psr = makeplatform.AttrParser( [['foo',int,'desc']] )
        self.assertRaises( Exception, psr.parse_in_place, {'bar':5} )

    def test_the_preset_platform_options(self):
        ""
        apsr = makeplatform.AttrParser()

        popts = { 'batchsys':'slurm',          'ppn':'5',
                  'dpn':'7',                   'queue':'admin',
                  'account':'fy666',           'variation':'knl',
                  'walltime':'2:34',           'maxprocs':'23',
                  'maxdevices':'33',           'maxqtime':'3600',
                  'maxsubs':'11',              'QoS':'long',
                  'testingdir':'/path',        'extra_flags':'--foo=bar',
                }
        apsr.parse_in_place( popts )
        self.assertEqual( popts,
                { 'batchsys':'slurm',          'ppn':5,
                  'dpn':7,                     'queue':'admin',
                  'account':'fy666',           'variation':'knl',
                  'walltime':'2:34',           'maxprocs':23,
                  'maxdevices':33,             'maxqtime':3600,
                  'maxsubs':11,                'QoS':'long',
                  'testingdir':'/path',        'extra_flags':'--foo=bar',
                } )

        popts = { 'processors_per_node':'5',   'devices_per_node':'7',
                  'q':'admin',                 'PT':'fy666',
                  'submit_flags':'--foo=bar',
                }
        apsr.parse_in_place( popts )
        self.assertEqual( popts,
                { 'ppn':5,                     'dpn':7,
                  'queue':'admin',             'account':'fy666',
                  'extra_flags':'--foo=bar',
                } )

        popts = { 'cores_per_node':'5', 'partition':'admin', }
        apsr.parse_in_place( popts )
        self.assertEqual( popts, { 'ppn':5, 'queue':'admin', } )

    def test_initialize_platform_config_from_platform_plugin(self):
        ""
        util.writefile( 'adir/platform_plugin.py', """
            def initialize( platobj ):
                platobj.setattr( 'ppn', 3 )
            """ )
        adir = abspath( 'adir' )

        apsr = makeplatform.AttrParser()

        with vtu.clean_sys_path():
            platcfg = makeplatform.PlatformConfig( apsr, {}, None, None )
            makeplatform.initialize_platform( platcfg )
            assert platcfg.getattr( 'ppn', None ) is None

        with vtu.clean_sys_path():
            platcfg = makeplatform.PlatformConfig( apsr, {}, None, None )
            sys.path.insert( 0, adir )
            makeplatform.initialize_platform( platcfg )
            self.assertEqual( platcfg.getattr( 'ppn', None ), 3 )

    def test_Platform_object_construction(self):
        ""
        plat = makeplatform.create_Platform_instance(
                    None, 'direct', {},
                    None, None, None, None,
                    None, None )

        platopts = { 'q':'justdoit', 'PT':'fy666', 'walltime':'2:34' }
        plat = makeplatform.create_Platform_instance(
                    'XBox', 'batch', platopts,
                    10, 20, 2, 4,
                    ['dbg'], ['symbols'] )

        assert plat.getName() == 'XBox'
        assert plat.getMaxSize() == (20,4)
        assert plat.getattr( 'queue' ) == 'justdoit'
        assert plat.getattr( 'account' ) == 'fy666'
        assert plat.getattr( 'walltime' ) == '2:34'

    def test_platform_option_precedence(self):
        """
            1) command line dedicated, such as -N
            2) --platopts on command line
            3) platform plugin
            4) probing
        """
        util.writefile( 'adir/platform_plugin.py', """
            def initialize( platobj ):
                platobj.setattr( 'maxprocs', 3 )
                platobj.setattr( 'maxdevices', 9 )
            """ )
        adir = abspath( 'adir' )

        with vtu.clean_sys_path():

            # no plugin or command line
            plat = makeplatform.create_Platform_instance(
                        'XBox', 'direct', {},
                        None, None, None, None,
                        [], [] )
            mxnp,mxnd = plat.getMaxSize()
            assert mxnp and mxnp > 0 and mxnd == 0

            sys.path.insert( 0, adir )

            # just plugin
            plat = makeplatform.create_Platform_instance(
                        'XBox', 'direct', {},
                        None, None, None, None,
                        [], [] )
            self.assertEqual( list( plat.getMaxSize() ), [3,9] )

            # plugin plus --platopts
            platopts = { 'maxprocs':'5', 'maxdevices':'7' }
            plat = makeplatform.create_Platform_instance(
                        'XBox', 'direct', platopts,
                        None, None, None, None,
                        [], [] )
            self.assertEqual( list( plat.getMaxSize() ), [5,7] )

            # plugin plus --platopts plus dedicated command line
            platopts = { 'maxprocs':'5', 'maxdevices':'7' }
            plat = makeplatform.create_Platform_instance(
                        'XBox', 'direct', platopts,
                        None, 20, None, 4,
                        [], [] )
            self.assertEqual( list( plat.getMaxSize() ), [20,4] )


class modes( vtu.vvtestTestCase ):

    def setUp(self):
        ""
        vtu.vvtestTestCase.setUp( self )

        util.writefile( 'cfg/platform_plugin.py', """
            def initialize( platobj ):
                platobj.setattr( 'maxprocs', 27 )
                platobj.setattr( 'maxdevices', 11 )
                platobj.setattr( 'cores_per_node', 17 )
                platobj.setattr( 'devices_per_node', 19 )
            """ )
        self.cfgdir = abspath( 'cfg' )

        util.writefile( 'nocfg/platform_plugin.py', """
            def initialize( platobj ):
                pass
            """ )
        self.nocfg = abspath( 'nocfg' )

    def test_direct_mode_getMaxSize(self):
        """
        max procs:
            1) command line max
            2) plugin max
            3) procs per node
            4) system probe
            5) the value 4
        max devices:
            1) command line max
            2) plugin max
            3) devices per node
            4) command line num devices
            5) zero
        """
        # the system probe should always return a positive integer for np
        plat = newplatform( self.nocfg, 'direct', cmdmax=(None,None) )
        np,nd = plat.getMaxSize()
        assert type(np) == type(2) and np > 0 and nd == 0

        plat = newplatform( self.nocfg, 'direct', cmdmax=(23,None), )
        self.assertEqual( plat.getMaxSize(), (23,0) )

        plat = newplatform( self.nocfg, 'direct', cmdmax=(23,7) )
        self.assertEqual( plat.getMaxSize(), (23,7) )

        plat = newplatform( self.nocfg, 'direct', cmdsize=(None,15), cmdmax=(None,None) )
        np,nd = plat.getMaxSize()
        self.assertEqual( nd, 15 )

        plat = newplatform( self.nocfg, 'direct', cmdsize=(None,15), cmdmax=(None,13) )
        np,nd = plat.getMaxSize()
        self.assertEqual( nd, 13 )

        plat = newplatform( self.cfgdir, 'direct', cmdmax=(None,None) )
        self.assertEqual( plat.getMaxSize(), (27,11) )

        plat = newplatform( self.cfgdir, 'direct', cmdmax=(23,7) )
        self.assertEqual( plat.getMaxSize(), (23,7) )

        attrs = {'ppn':'13','dpn':'15'}
        plat = newplatform( self.nocfg, 'direct', cmdmax=(None,None), attrs=attrs )
        self.assertEqual( plat.getMaxSize(), (13,15) )

        attrs = {'ppn':'13','dpn':'15'}
        plat = newplatform( self.nocfg, 'direct', cmdmax=(23,7), attrs=attrs )
        self.assertEqual( plat.getMaxSize(), (23,7) )

    def test_batch_mode_getMaxSize(self):
        """
        max procs:
            1) command line max
            2) plugin max
            3) None (no maximum)
        max devices:
            1) command line max
            2) plugin max
            3) if dpn set, then None (no maximum), else zero
        """
        plat = newplatform( self.nocfg, 'batch', cmdmax=(None,None) )
        self.assertEqual( plat.getMaxSize(), (None,0) )

        attrs = {'dpn':3}
        plat = newplatform( self.nocfg, 'batch', cmdmax=(None,None), attrs=attrs )
        self.assertEqual( plat.getMaxSize(), (None,None) )

        plat = newplatform( self.nocfg, 'batch', cmdmax=(23,None) )
        self.assertEqual( plat.getMaxSize(), (23,0) )

        plat = newplatform( self.nocfg, 'batch', cmdmax=(23,7) )
        self.assertEqual( plat.getMaxSize(), (23,7) )

        plat = newplatform( self.cfgdir, 'batch', cmdmax=(None,None) )
        self.assertEqual( plat.getMaxSize(), (27,11) )

        plat = newplatform( self.cfgdir, 'batch', cmdmax=(23,7) )
        self.assertEqual( plat.getMaxSize(), (23,7) )

    def test_batchjob_mode_getMaxSize(self):
        """
        Since procs per node is always positive, the max np is always num_nodes*ppn
        If devices per node is positive, then max devices will be num_nodes*dpn
        These values will be set on the batch job vvtest command line with -N
        and --max-devices
        """
        plat = newplatform( self.nocfg, 'batchjob', cmdmax=(23,None) )
        self.assertEqual( plat.getMaxSize(), (23,None) )

        plat = newplatform( self.nocfg, 'batchjob', cmdmax=(23,7) )
        self.assertEqual( plat.getMaxSize(), (23,7) )

        plat = newplatform( self.cfgdir, 'batchjob', cmdmax=(23,None) )
        self.assertEqual( plat.getMaxSize(), (23,None) )

        plat = newplatform( self.cfgdir, 'batchjob', cmdmax=(23,7) )
        self.assertEqual( plat.getMaxSize(), (23,7) )

    def test_direct_mode_num_cores_and_num_devices(self):
        ""
        # the system probe should always return a positive integer for np
        plat = newplatform( self.nocfg, 'direct', cmdsize=(None,None) )
        np,nd = plat.getSize()
        assert type(np) == type(2) and np > 0 and nd is None

        plat = newplatform( self.nocfg, 'direct', cmdmax=(23,None) )
        self.assertEqual( plat.getSize(), (23,None) )

        plat = newplatform( self.nocfg, 'direct', cmdmax=(23,7) )
        self.assertEqual( plat.getSize(), (23,7) )

        plat = newplatform( self.cfgdir, 'direct', cmdmax=(None,None) )
        self.assertEqual( plat.getSize(), (27,11) )

        plat = newplatform( self.cfgdir, 'direct', cmdmax=(23,7) )
        self.assertEqual( plat.getSize(), (23,7) )

        plat = newplatform( self.nocfg,  'direct', cmdsize=(2,None), cmdmax=(23,None) )
        self.assertEqual( plat.getSize(), (2,None) )

        plat = newplatform( self.nocfg,  'direct', cmdsize=(2,5),    cmdmax=(23,7) )
        self.assertEqual( plat.getSize(), (2,5) )

        plat = newplatform( self.cfgdir, 'direct', cmdsize=(2,None), cmdmax=(None,None) )
        self.assertEqual( plat.getSize(), (2,11) )

        plat = newplatform( self.cfgdir, 'direct', cmdsize=(2,5),    cmdmax=(23,7) )
        self.assertEqual( plat.getSize(), (2,5) )

    def test_batch_mode_num_cores_and_num_devices(self):
        """
        Since no tests are run in batch mode, the number of cores/devices is
        not used.
        """
        plat = newplatform( self.nocfg, 'batch', cmdsize=(None,None) )
        self.assertEqual( plat.getSize(), (None,None) )
        self.assertEqual( plat.getMaxSize(), (None,0) )

        plat = newplatform( self.nocfg, 'batch', cmdsize=(8,4) )
        self.assertEqual( plat.getSize(), (8,4) )
        self.assertEqual( plat.getMaxSize(), (None,0) )

    def test_batchjob_mode_num_cores_and_num_devices(self):
        """
        For batch jobs, only the command line options should be used. Either
            1) num cores/devices is specified, or
            2) max num cores/devices is specified
        If max is given but not number, then the number will be set to the max.
        """
        plat = newplatform( self.nocfg, 'batchjob', cmdsize=(4,2) )
        self.assertEqual( plat.getSize(), (4,2) )

        plat = newplatform( self.nocfg, 'batchjob', cmdsize=(None,None), cmdmax=(5,3) )
        self.assertEqual( plat.getSize(), (5,3) )

        plat = newplatform( self.nocfg, 'batchjob', cmdsize=(4,2), cmdmax=(5,3) )
        self.assertEqual( plat.getSize(), (4,2) )

        plat = newplatform( self.cfgdir, 'batchjob', cmdsize=(4,2) )
        self.assertEqual( plat.getSize(), (4,2) )

        plat = newplatform( self.cfgdir, 'batchjob', cmdsize=(None,None), cmdmax=(5,3) )
        self.assertEqual( plat.getSize(), (5,3) )

        plat = newplatform( self.cfgdir, 'batchjob', cmdsize=(4,2), cmdmax=(5,3) )
        self.assertEqual( plat.getSize(), (4,2) )

        # this is unrealistic, but correct in theory
        plat = newplatform( self.nocfg, 'batchjob', cmdsize=(None,None) )
        self.assertEqual( plat.getSize(), (None,None) )

        plat = newplatform( self.cfgdir, 'batchjob', cmdsize=(None,None) )
        self.assertEqual( plat.getSize(), (None,None) )

    def test_direct_mode_compute_node_size(self):
        """
        By default in direct mode, the whole workstation is treated as a single
        node. But it uses values for ppn and dpn if given on the command line
        or in the platform plugin.
        """
        plat = newplatform( self.nocfg, 'direct', cmdmax=(None,None), attrs={} )
        ppn,dpn = plat.getNodeSize()
        assert ppn and ppn > 0 and dpn is None

        plat = newplatform( self.nocfg, 'direct', cmdmax=(5,7), attrs={} )
        self.assertEqual( plat.getNodeSize(), (5,7) )

        plat = newplatform( self.nocfg, 'direct', cmdmax=(None,None),
                            attrs={'ppn':5,'dpn':7} )
        self.assertEqual( plat.getNodeSize(), (5,7) )

        plat = newplatform( self.cfgdir, 'direct', cmdmax=(None,None), attrs={} )
        self.assertEqual( plat.getNodeSize(), (17,19) )

        plat = newplatform( self.cfgdir, 'direct', cmdmax=(5,7), attrs={} )
        self.assertEqual( plat.getNodeSize(), (17,19) )

        plat = newplatform( self.cfgdir, 'direct', cmdmax=(None,None),
                            attrs={'ppn':5,'dpn':7} )
        self.assertEqual( plat.getNodeSize(), (5,7) )

    def test_batch_mode_compute_node_size(self):
        """
        In batch mode, the "subprocs" batch system is special - it uses ppn
        and dpn if defined, otherwise it uses the max cores/devices.
        For other batch systems, at least ppn must be set; it is an error
        otherwise.
        """
        attrs = {'batchsys':'subprocs'}

        plat = newplatform( self.nocfg, 'batch', cmdmax=(None,None), attrs=attrs )
        ppn,dpn = plat.getNodeSize()
        assert ppn and ppn > 0 and dpn == 0

        plat = newplatform( self.cfgdir, 'batch', attrs=attrs )
        self.assertEqual( plat.getNodeSize(), (17,19) )

        plat = newplatform( self.nocfg, 'batch', cmdmax=(5,7), attrs=attrs )
        self.assertEqual( plat.getNodeSize(), (5,7) )

        attrs = {'batchsys':'subprocs','ppn':'8','dpn':'3'}
        plat = newplatform( self.nocfg, 'batch', cmdmax=(5,7), attrs=attrs )
        self.assertEqual( plat.getNodeSize(), (8,3) )

        attrs = {'batchsys':'slurm'}

        # ppn must get set
        self.assertRaises( Exception,
            newplatform, self.nocfg, 'batch', cmdmax=(5,7), attrs=attrs )

        plat = newplatform( self.cfgdir, 'batch', cmdmax=(5,7), attrs=attrs )
        self.assertEqual( plat.getNodeSize(), (17,19) )

        attrs = {'batchsys':'slurm','ppn':'9'}
        plat = newplatform( self.nocfg, 'batch', cmdmax=(5,7), attrs=attrs )
        self.assertEqual( plat.getNodeSize(), (9,None) )

        attrs = {'batchsys':'slurm','ppn':'9','dpn':'25'}
        plat = newplatform( self.nocfg, 'batch', cmdmax=(5,7), attrs=attrs )
        self.assertEqual( plat.getNodeSize(), (9,25) )

    def test_batchjob_mode_compute_node_size(self):
        """
        In batch jobs, the ppn and dpn are specified on the vvtest command line.
        """
        # ppn must get set
        self.assertRaises( Exception,
            newplatform, self.nocfg, 'batchjob', cmdmax=(5,7), attrs={} )

        attrs = {'ppn':'5','dpn':7}
        plat = newplatform( self.nocfg, 'batchjob', cmdmax=(5,7), attrs=attrs )
        self.assertEqual( plat.getNodeSize(), (5,7) )

        attrs = {'ppn':'5'}
        plat = newplatform( self.nocfg, 'batchjob', cmdmax=(5,None), attrs=attrs )
        self.assertEqual( plat.getNodeSize(), (5,None) )


def newplatform( cfgdir, mode, cmdsize=(None,None),
                               cmdmax=(None,None),
                               attrs={'ppn':1} ):
    ""
    np,nd = cmdsize
    nprocs,ndevice = cmdmax

    with vtu.clean_sys_path():
        sys.path.insert( 0, cfgdir )

        plat = makeplatform.create_Platform_instance(
                    None, mode, attrs,
                    np, nprocs, nd, ndevice, None, None )

    return plat


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
