#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST: vvtest

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
from os.path import abspath
from os.path import join as pjoin
import time
import shutil
from glob import glob
import stat

import vvtestutils as vtu
import testutils as util
from testutils import print3


class rundir_usage( vtu.vvtestTestCase ):

    def test_using_the_M_option(self):
        ""
        os.mkdir( 'mir' )

        util.writefile( "src/atest.vvt", """
            import os, sys
            dL = []
            for i in range(1000):
                d1 = os.getcwd()
                dL.append( os.path.basename(d1) )
                os.chdir( '..' )
                d2 = os.getcwd()
                if os.path.samefile( d1, d2 ):
                    break
            dL.reverse()
            print ( 'PWD='+repr( os.sep.join( dL ) ) )
            """)
        time.sleep(1)

        vrun = vtu.runvvtest( '-M', abspath('mir'), 'src' )
        vrun.assertCounts( total=1, npass=1 )

        pwd = eval( vrun.greplogs( 'PWD=' )[-1].split( 'PWD=', 1 )[1] )
        trd = util.globfile( pjoin( abspath('mir'), 'TestResults*', 'atest' ) )
        assert os.path.samefile( pwd, trd )
        assert os.path.islink( vrun.resultsDir() )

        vrun = vtu.runvvtest( '-R', chdir=vrun.resultsDir() )
        vrun.assertCounts( total=1, npass=1 )
        pwd2 = eval( vrun.greplogs( 'PWD=' )[-1].split( 'PWD=', 1 )[1] )
        assert pwd == pwd2

    def test_using_M_option_when_PWD_is_not_writable(self):
        ""
        # magic: not done; the desired behavior is to have the mirror
        #        directory created and just cd there and run
        #
        #   the changes needed expose a more general problem, which is that
        #   relative pathing is tangled up in the startup sequence
        #
        #   fixing the relative pathing would allow --run-dir to be an
        #   absolute path as well
        return

        os.mkdir( 'mir' )

        cdir = 'work'
        util.writefile( cdir+'/atest.vvt', """
            import vvtest_util as vvt
            """ )

        savefm = stat.S_IMODE( os.stat(cdir)[stat.ST_MODE] )
        fm = savefm & ( ~( stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH ) )
        os.chmod( cdir, fm )

        time.sleep(1)

        try:
            vrun = vtu.runvvtest( '-M', abspath('mir'), chdir=cdir )
        finally:
            os.chmod( cdir, savefm )

        assert len( glob( cdir+'/TestResults*' ) ) == 0
        vrun.assertCounts( total=1, npass=1 )

    def test_using_rundir_option(self):
        ""
        write_unit_test_files()
        time.sleep(1)

        for batch in [False,True]:

            vtu.remove_results()

            if os.path.exists( 'myrundir' ):
                shutil.rmtree( 'myrundir' )

            vrun = vtu.runvvtest( '--run-dir myrundir', batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            assert len( glob( 'TestResults*' ) ) == 0
            assert os.path.isdir( 'myrundir' )
            logL = glob( 'myrundir/test*/execute.log' )
            assert len(logL) == 2

    def test_using_rundir_option_and_M_option(self):
        ""
        for batch in [False,True]:

            util.rmallfiles()

            write_unit_test_files()
            os.mkdir( 'mymirror' )
            time.sleep(1)

            mymir = os.path.abspath( 'mymirror' )
            vrun = vtu.runvvtest( '--run-dir myrundir -M '+mymir, batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            assert len( glob( 'TestResults*' ) ) == 0

            assert os.path.islink( 'myrundir' )
            lnk = os.readlink( 'myrundir' )
            assert os.path.exists( lnk )
            assert os.path.samefile( lnk, 'mymirror/myrundir' )

            logL = glob( 'mymirror/myrundir/test*/execute.log' )
            assert len(logL) == 2

            logL = glob( 'myrundir/test*/execute.log' )
            assert len(logL) == 2

    def test_rundir_can_only_be_a_single_word(self):
        ""
        write_unit_test_files()
        time.sleep(1)

        self.assertRaises( Exception, vtu.runvvtest, '--run-dir foo/bar' )
        self.assertRaises( Exception, vtu.runvvtest,
                           '--run-dir '+os.path.abspath('myrundir') )


def write_unit_test_files():
    ""
    util.writescript( 'testX.vvt', """
        #!"""+sys.executable+"""
        #VVT: link = auxfile.txt
        import os, sys
        import vvtest_util as vvt
        fp = open( 'auxfile.txt', 'r' )
        sys.stdout.write( fp.read() )
        sys.stdout.flush()
        fp.close()
        """ )
    util.writefile( "testY.xml", """
        <rtest name="testY">
          <link_files> auxfile.txt </link_files>
          <execute>
            cat auxfile.txt
          </execute>
        </rtest>""" )
    util.writefile( "auxfile.txt", """
        <rtest name="testY">
          <execute>
            cat auxfile.txt
          </execute>
        </rtest>""" )


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
