#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

"""
A python front end to the script_util.py platform, parameter, and option
expression evaluators. Used by script_util.sh.
"""

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import getopt

import vvtest_util as vvt
from script_util.exprutils import platform_expr, parameter_expr, option_expr

optL,argL = getopt.getopt( sys.argv[1:], 'f:p:o:' )

for n,v in optL:

    if n == '-p':
        if parameter_expr( v ):
            sys.stdout.write( 'true' )
        else:
            sys.stdout.write( 'false' )
        break

    elif n == '-f':
        if platform_expr( v ):
            sys.stdout.write( 'true' )
        else:
            sys.stdout.write( 'false' )
        break

    elif n == '-o':
        if option_expr( v ):
            sys.stdout.write( 'true' )
        else:
            sys.stdout.write( 'false' )
        break
