#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util
print3 = util.print3

import libvvtest.testcase as testcase
import libvvtest.execlist as execlist
from libvvtest.execlist import TestExecList
from libvvtest.TestList import TestList


class iterating_the_backlog( vtu.vvtestTestCase ):

    def test_iterate_backlog_by_size_and_runtime(self):
        ""
        tests = vtu.make_TestCase_list()

        back = execlist.TestBacklog()
        for tcase in tests:
            back.insert( tcase )

        back.sort()

        tL = []
        for tcase in back.iterate():
            tL.append( runtime_tuple(tcase) )
            print3( tL[-1] )

        assert tL == [ ['sdir/atest1.np=2', 2, 22],
                       ['sdir/atest0.np=2', 2, 12],
                       ['sdir/atest1.np=1', 1, 21],
                       ['sdir/atest0.np=1', 1, 11] ]

    def test_consuming_the_backlog_by_size_and_runtime(self):
        ""
        tests = vtu.make_TestCase_list()

        back = execlist.TestBacklog()
        for tcase in tests:
            back.insert( tcase )

        back.sort()

        tcase = back.pop( max_size=4,
                          constraint=lambda tc: tc.getStat().getRuntime() < 20 )

        print3( runtime_tuple(tcase) )
        assert runtime_tuple(tcase) == [ 'sdir/atest0.np=2', 2, 12 ]

        tcase = back.pop( max_size=1,
                          constraint=lambda tc: tc.getStat().getRuntime() < 20 )

        print3( runtime_tuple(tcase) )
        assert runtime_tuple(tcase) == [ 'sdir/atest0.np=1', 1, 11 ]

        tL = []
        for tcase in back.consume():
            tL.append( runtime_tuple(tcase) )
            print3( tL[-1] )

        assert tL == [ [ 'sdir/atest1.np=2', 2, 22 ],
                       [ 'sdir/atest1.np=1', 1, 21 ] ]

    def test_iterate_backlog_by_size_and_timeout(self):
        ""
        tests = vtu.make_TestCase_list( timespec='timeout' )

        back = execlist.TestBacklog()
        for tcase in tests:
            back.insert( tcase )

        back.sort( secondary='timeout' )

        tL = []
        for tcase in back.consume():
            tL.append( timeout_tuple(tcase) )
            print3( tL[-1] )

        assert tL == [ [ 'sdir/atest1.np=2', 2, 22 ],
                       [ 'sdir/atest0.np=2', 2, 12 ],
                       [ 'sdir/atest1.np=1', 1, 21 ],
                       [ 'sdir/atest0.np=1', 1, 11 ] ]

    def test_iterate_TestExecList_by_size_and_timeout(self):
        ""
        tlist, xlist = vtu.make_fake_TestExecList_with_timeouts()

        xlist.sortBySizeAndTimeout()

        tL = []
        while True:
            tcase = xlist.getNextTest()
            if tcase:
                tL.append( timeout_tuple(tcase) )
                xlist.moveToStarted( tcase )
            else:
                break

        assert tL == [ [ 'sdir/atest1.np=2', 2, 22 ],
                       [ 'sdir/atest0.np=2', 2, 12 ],
                       [ 'sdir/atest1.np=1', 1, 21 ],
                       [ 'sdir/atest0.np=1', 1, 11 ] ]


def runtime_tuple( tcase ):
    ""
    return [ tcase.getSpec().getDisplayString(),
             int( tcase.getSpec().getParameterValue('np') ),
             tcase.getStat().getRuntime() ]

def timeout_tuple( tcase ):
    ""
    return [ tcase.getSpec().getDisplayString(),
             int( tcase.getSpec().getParameterValue('np') ),
             tcase.getSpec().getAttr('timeout') ]


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
