#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util
print3 = util.print3

import libvvtest.testcase as testcase
from libvvtest.execlist import TestExecList
from libvvtest.TestList import TestList


class iterating_the_backlog( vtu.vvtestTestCase ):

    def test_iterating_by_size_and_timeout(self):
        ""
        tlist, xlist = vtu.make_fake_TestExecList_with_timeouts()

        xlist.sortBySizeAndTimeout()

        tL = []
        while True:
            tcase = xlist.getNextTest()
            if tcase:
                tspec = tcase.getSpec()
                tL.append( [ tspec.getName(),
                             tspec.getParameterValue('np'),
                             tspec.getAttr('timeout') ] )
                xlist.moveToStarted( tcase )
            else:
                break

        assert tL == [ [ 'atest1', '2', 22 ],
                       [ 'atest0', '2', 12 ],
                       [ 'atest1', '1', 21 ],
                       [ 'atest0', '1', 11 ] ]


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
