#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
from os.path import abspath, basename
import time
import glob
import stat
import struct

import vvtestutils as vtu
import testutils as util
from testutils import print3

import libvvtest.testlistio as tio
import libvvtest.TestList as TestList
import libvvtest.TestSpec as TestSpec
from libvvtest.testcase import TestCase
import libvvtest.paramset as ParameterSet


class TestSpec_to_and_from_string( vtu.vvtestTestCase ):

    def setUp(self):
        vtu.vvtestTestCase.setUp( self, cleanout=False )

    def test_converting_a_test_to_a_string_and_back(self):
        ""
        tcase = create_TestCase()

        sid = tio.test_to_string( tcase )
        assert '\n' not in sid
        tcase2 = tio.string_to_test( sid )

        assert_TestCase_same_as_fake( tcase2 )

    def test_converting_an_analyze_test_to_string_and_back(self):
        ""
        tcase = create_fake_analyze_TestCase()

        sid = tio.test_to_string( tcase )
        tcase2 = tio.string_to_test( sid )

        assert tcase2.getSpec().isAnalyze()


class test_list_file_read_write( vtu.vvtestTestCase ):

    def test_the_start_and_end_dates_are_written_into_the_file(self):
        ""
        tlw = tio.TestListWriter( 'tests.out' )
        tlw.start()
        time.sleep(2)
        tlw.finish()
        time.sleep(1)

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()
        d1 = tlr.getStartDate()
        d2 = tlr.getFinishDate()
        assert d2-d1 > 1 and d2-d1 < 5
        assert time.time() - d1 < 10

    def test_write_then_read_test_list_attributes(self):
        ""
        tlw = tio.TestListWriter( 'tests.out' )
        tlw.start( strname='some value', intname=101, floatname=1.01 )
        tlw.finish()
        time.sleep(1)

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()

        assert tlr.getAttr( 'foobar', 'default value' ) == 'default value'
        self.assertRaises( Exception, tlr.getAttr, 'foobar' )
        assert tlr.getAttr( 'strname' ) == 'some value'
        assert tlr.getAttr( 'intname' ) == 101
        assert tlr.getAttr( 'floatname' ) == 1.01

    def test_write_and_read_a_test(self):
        ""
        tcase = vtu.make_fake_TestCase( result='pass', name='atest' )

        tlw = tio.TestListWriter( 'tests.out' )
        tlw.start()
        tlw.append( tcase )
        tlw.finish()

        time.sleep(1)

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()

        tcase = get_single_test_from_test_list( tlr )
        tspec = tcase.getSpec()
        assert tspec.getDisplayString() == 'sdir/atest.np=4'
        kwds = tspec.getKeywords( include_implicit=False )
        assert 'key1' in kwds and 'key2' in kwds
        assert tcase.getStat().isDone()

    def test_read_an_unfinished_test_results_file(self):
        ""
        tcase = vtu.make_fake_TestCase( result='pass', name='atest' )

        tlw = tio.TestListWriter( 'tests.out' )
        tlw.start()
        tlw.append( tcase )
        # an "unfinished" file does not have tlw.finish() called

        time.sleep(1)

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()

        tm = time.time()
        assert tm - tlr.getStartDate() < 5
        assert tlr.getFinishDate() == None
        tcase = get_single_test_from_test_list( tlr )
        assert tcase.getSpec().getDisplayString() == 'sdir/atest.np=4'

    def write_with_include_file(self, tcase, skip_completed_mark=False):
        ""
        tlw = tio.TestListWriter( 'tests.out' )
        tlw.start()

        tlw.addIncludeFile( 'tests.0' )
        tlw.append( tcase )

        tstart = time.time()
        time.sleep(2)

        write_test_sequence_to_file( 'tests.0', tcase )

        if not skip_completed_mark:
            tlw.append( tcase )
            tlw.includeFileCompleted( 'tests.0' )

        time.sleep(2)

        tlw.finish()

        tdone = time.time()
        time.sleep(1)

        return tstart, tdone

    def test_write_and_read_using_an_include_file(self):
        ""
        tcase = vtu.make_fake_TestCase( result='notrun', name='atest' )

        tstart,tdone = self.write_with_include_file( tcase )

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()

        tcase = get_single_test_from_test_list( tlr )
        assert tcase.getSpec().getDisplayString() == 'sdir/atest.np=4'
        assert tcase.getStat().passed()

        tm = tlr.getStartDate()
        assert tstart >= tm and tstart-tm < 2
        tm = tlr.getFinishDate()
        assert tdone >= tm and tdone-tm < 2

    def test_include_files_are_not_read_if_marked_completed(self):
        ""
        tcase = vtu.make_fake_TestCase( result='notrun', name='atest' )

        self.write_with_include_file( tcase )

        os.remove( 'tests.0' )
        time.sleep(1)

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()

        tcase = get_single_test_from_test_list( tlr )
        assert tcase.getSpec().getDisplayString() == 'sdir/atest.np=4'
        assert tcase.getStat().passed()

    def test_include_files_are_read_if_not_marked_completed(self):
        ""
        tcase = vtu.make_fake_TestCase( result='notrun', name='atest' )

        self.write_with_include_file( tcase, skip_completed_mark=True )

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()

        tcase = get_single_test_from_test_list( tlr )
        assert tcase.getSpec().getDisplayString() == 'sdir/atest.np=4'
        assert tcase.getStat().passed()

        # without the include file, the final test status is lost
        os.remove( 'tests.0' )
        time.sleep(1)

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()

        tcase = get_single_test_from_test_list( tlr )
        assert tcase.getSpec().getDisplayString() == 'sdir/atest.np=4'
        assert tcase.getStat().isNotrun()

    def test_include_files_are_relative_to_parent_file_directory(self):
        ""
        write_test_list_with_include( 'tests.out', 'subdir/tests.0' )
        os.mkdir( 'rundir' )
        time.sleep(1)

        rootdir = os.getcwd()
        tfile = abspath( 'tests.out' )

        os.chdir( 'rundir' )
        tlr = tio.TestListReader( tfile )
        tlr.read()

        tcase = get_single_test_from_test_list( tlr )
        assert_TestCase_same_as_fake( tcase, rootdir )

    def test_write_a_test_file_then_scan_it_for_the_finish_date(self):
        ""
        write_test_list_with_fake_test( 'tests.out' )
        time.sleep(1)

        tlr = tio.TestListReader( 'tests.out' )
        tm = tlr.scanForFinishDate()
        assert tm and (time.time() - tm) < 10

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()
        assert abs( tlr.getFinishDate() - tm ) < 2

    def test_scan_an_unfinished_test_results_file(self):
        ""
        tlw = tio.TestListWriter( 'tests.out' )
        tlw.start()
        tcase = create_TestCase_with_results()
        tlw.append( tcase )

        time.sleep(1)

        tlr = tio.TestListReader( 'tests.out' )
        tm = tlr.scanForFinishDate()
        assert tm == None

    def test_read_unfinished_results_file_with_include(self):
        ""
        write_test_list_with_include( 'tests.out', 'tests.0', finish=False )
        time.sleep(1)

        tlr = tio.TestListReader( 'tests.out' )
        tlr.read()

        tcase = get_single_test_from_test_list( tlr )
        assert_TestCase_same_as_fake( tcase )

        tm = tlr.getStartDate()
        assert tm != None and time.time() - tm < 10
        assert tlr.getFinishDate() == None


class TestList_results_file( vtu.vvtestTestCase ):

    def test_write_a_test_list_file_then_read_it(self):
        ""
        write_TestList_with_fake_test()
        time.sleep(1)
        read_TestList_and_check_fake_test()

    def test_write_a_test_list_then_results_then_read_it(self):
        ""
        tl = write_TestList_with_fake_test()
        time.sleep(1)
        rfile = write_TestList_fake_results( tl )
        time.sleep(1)

        bname = basename( rfile )
        assert bname.startswith( 'testlist' ) and bname != 'testlist'

        fn = util.globfile( 'testlist.*' )
        assert fn == bname

        read_TestList_and_check_fake_test()

    def test_a_workflow_using_a_rundate(self):
        ""
        tl = write_TestList_with_fake_test( addrundate=True )
        sfx = tl.getResultsSuffix()
        time.sleep(2)

        tl = TestList.TestList()
        tl.readTestList()
        assert tl.getResultsSuffix() == sfx
        rfile = write_TestList_fake_results( tl )
        time.sleep(1)

        assert rfile.endswith( sfx )
        read_TestList_and_check_fake_test()

    def test_results_workflow_with_include_file(self):
        ""
        os.mkdir( 'subdir' )
        time.sleep(1)

        # the origin test list
        tl = write_TestList_with_fake_test()
        time.sleep(1)

        # create suffix for the include files
        sfx = tl.setResultsSuffix()

        # write include test list file containing suffix attribute
        tcase = list( tl.getTests() )[0]
        tlincl = TestList.TestList( directory='subdir', identifier=3 )
        tlincl.setResultsSuffix( sfx )
        tlincl.addTest( tcase )
        tlincl.stringFileWrite( extended=True )
        time.sleep(1)

        # start the comprehensive results file (with the include in it)
        tl.initializeResultsFile()
        tl.addIncludeFile( tlincl.getResultsFilename() )
        time.sleep(1)

        # create the sublist test results
        tlsub = TestList.TestList( directory='subdir', identifier=3 )
        tlsub.readTestList()
        write_TestList_fake_results( tlsub )
        time.sleep(1)

        tl.writeFinished()
        time.sleep(1)

        # should be able to read comprehensive results file
        read_TestList_and_check_fake_test()

    def test_read_an_unfinished_test_list_file(self):
        ""
        tcase = create_TestCase()

        tl = TestList.TestList()
        tl.addTest( tcase )
        tl.stringFileWrite()
        rfile = tl.initializeResultsFile()
        tl.appendTestResult( tcase )

        time.sleep(1)

        tl = TestList.TestList()
        tl.readTestResults( rfile )

        tm = tl.getDateStamp()
        assert tm != None and time.time() - tm < 10
        assert tl.getFinishDate() == None

        read_TestList_and_check_fake_test()


class scan_finish_mark( vtu.vvtestTestCase ):

    def test_scan_an_unfinished_test_list_file(self):
        ""
        tl = TestList.TestList()
        rfile = tl.initializeResultsFile()
        tcase = create_TestCase()
        tl.appendTestResult( tcase )

        time.sleep(1)

        tlr = tio.TestListReader( rfile )
        tm = tlr.scanForFinishDate()
        assert tm == None

    def test_function_to_test_for_finished_date(self):
        ""
        tl = TestList.TestList()
        rfile = tl.initializeResultsFile()
        tcase = create_TestCase()
        tl.appendTestResult( tcase )

        time.sleep(1)

        assert tio.file_is_marked_finished( rfile ) == False

        tl.writeFinished()
        time.sleep(1)

        assert tio.file_is_marked_finished( rfile ) == True

    def test_for_finished_date_is_robust(self):
        ""
        # create file with binary data
        fp = open( 'afile.dat', 'wb' )
        buf = struct.pack( 'b', -128 ) * 10
        for i in range( -127, 128 ):
            buf += struct.pack( 'b', i ) * 10
        fp.write( buf )
        fp.close()
        time.sleep(1)

        assert tio.file_is_marked_finished( abspath('foobar') ) == False
        assert os.path.exists( 'afile.dat' )
        assert tio.file_is_marked_finished( 'afile.dat' ) == False


class format_versions( vtu.vvtestTestCase ):

    def test_the_current_testlist_file_format_version(self):
        ""
        write_TestList_with_fake_test( 'testlist' )
        time.sleep(1)

        tlr = tio.TestListReader( 'testlist' )
        tlr.read()
        assert tlr.getFileVersion() == 34

    def test_reading_testlist_format_version_31_is_an_exception(self):
        ""
        fp = open( 'testlist', 'w' )
        fp.write( example_testlist_version_31 )
        fp.close()
        time.sleep(1)

        tlr = tio.TestListReader( 'testlist' )
        self.assertRaises( Exception, tlr.read )

    def test_that_format_version_32_is_compatible_with_current_version(self):
        ""
        fp = open( 'testlist', 'w' )
        fp.write( example_testlist_version_32 )
        fp.close()
        time.sleep(1)

        tlr = tio.TestListReader( 'testlist' )
        tlr.read()
        assert tlr.getFileVersion() == 32
        assert len( tlr.getTests() ) == 3

    def test_read_version_33_testlist_with_includes(self):
        ""
        util.writefile( 'testlist', example_testlist_with_include_33 )
        util.writefile( 'testlist.0', example_include_0_version_33 )
        util.writefile( 'testlist.1', example_include_1_version_33 )
        util.writefile( 'testlist.2', example_include_2_version_33 )
        time.sleep(1)

        tlr = tio.TestListReader( 'testlist.1' )
        tlr.read()
        assert tlr.getFileVersion() == 33
        assert len( tlr.getTests() ) == 1
        tcase = list( tlr.getTests().values() )[0]
        assert tcase.getStat().getResultStatus() == 'pass'

        tlr = tio.TestListReader( 'testlist' )
        tlr.read()
        assert tlr.getFileVersion() == 33
        assert len( tlr.getTests() ) == 3
        for tcase in tlr.getTests().values():
            assert tcase.getStat().getResultStatus() == 'pass'


example_testlist_version_31 = \
"""
#VVT: Version = 31
#VVT: Date = Sat Sep 29 16:12:43 2018

py1 "/scratch/rrdrake/temp/prob" "py1.vvt" "_keywords_=bar foo py1" "state=Snotrun" "timeout=I3600" "xdate=I-1" "xtime=I-1"
py1 "/scratch/rrdrake/temp/prob" "py1.vvt" "_keywords_=bar foo py1" "state=Snotdone" "timeout=I3600" "xdate=I1538259163" "xtime=I-1"
py1 "/scratch/rrdrake/temp/prob" "py1.vvt" "_keywords_=bar foo py1" "result=Spass" "state=Sdone" "timeout=I3600" "xdate=I1538259163" "xtime=I1"

#VVT: Finish = Sat Sep 29 16:12:44 2018
"""

example_testlist_version_32 = \
"""
#VVT: Version = 32
#VVT: Start = ['Sun Mar  3 18:26:21 2019', 1551662781.325458]
#VVT: Attrs = {}

{'name': 'at', 'params': {'np': '1'}, 'attrs': {'xdate': -1, 'state': 'notrun', 'xtime': -1}, 'keywords': ['np', 'foo', 'bar', 'at'], 'path': 'at.vvt', 'root': '/scratch/rrdrake/temp/prob/analyze'}
{'name': 'at', 'params': {'np': '2'}, 'attrs': {'xdate': -1, 'state': 'notrun', 'xtime': -1}, 'keywords': ['np', 'foo', 'bar', 'at'], 'path': 'at.vvt', 'root': '/scratch/rrdrake/temp/prob/analyze'}
{'name': 'at', 'params': {}, 'attrs': {'xdate': -1, 'state': 'notrun', 'xtime': -1}, 'keywords': ['np', 'foo', 'bar', 'at'], 'path': 'at.vvt', 'root': '/scratch/rrdrake/temp/prob/analyze'}

#VVT: Finish = ['Sun Mar  3 18:26:21 2019', 1551662781.325975]
"""

# a batch test list before the includes were inlined (like a crash occurred)
example_testlist_with_include_33 = """\
#VVT: Version = 33
#VVT: Start = ['Mon Feb  3 19:25:27 2020', 1580783127.5386069]
#VVT: Attrs = {}

#VVT: Include = testlist.0
#VVT: Include = testlist.1
#VVT: Include = testlist.2
"""

example_include_0_version_33 = """\
#VVT: Version = 33
#VVT: Start = ['Mon Feb  3 19:25:34 2020', 1580783134.7756951]
#VVT: Attrs = {}

{'name': 'at', 'attrs': {'xdate': 1580783134.77, 'state': 'notdone', 'timeout': 3600, 'xtime': -1}, 'keywords': ['foo', 'bar'], 'path': 'at.vvt', 'root': '/scratch/rrdrake/temp/prob/analyze', 'paramset': {('np',): [['1'], ['2']]}}
{'name': 'at', 'attrs': {'xdate': 1580783134.77, 'state': 'done', 'timeout': 3600, 'xtime': 1, 'result': 'pass'}, 'keywords': ['foo', 'bar'], 'path': 'at.vvt', 'root': '/scratch/rrdrake/temp/prob/analyze', 'paramset': {('np',): [['1'], ['2']]}}

#VVT: Finish = ['Mon Feb  3 19:25:35 2020', 1580783135.7790179]
"""

example_include_1_version_33 = """\
#VVT: Version = 33
#VVT: Start = ['Mon Feb  3 19:25:27 2020', 1580783127.7365699]
#VVT: Attrs = {}

{'name': 'at', 'params': {'np': '2'}, 'attrs': {'xdate': 1580783127.73, 'state': 'notdone', 'timeout': 3600, 'xtime': -1}, 'keywords': ['foo', 'bar'], 'path': 'at.vvt', 'root': '/scratch/rrdrake/temp/prob/analyze'}
{'name': 'at', 'params': {'np': '2'}, 'attrs': {'xdate': 1580783127.73, 'state': 'done', 'timeout': 3600, 'xtime': 1, 'result': 'pass'}, 'keywords': ['foo', 'bar'], 'path': 'at.vvt', 'root': '/scratch/rrdrake/temp/prob/analyze'}

#VVT: Finish = ['Mon Feb  3 19:25:28 2020', 1580783128.73911]
"""

example_include_2_version_33 = """\
#VVT: Version = 33
#VVT: Start = ['Mon Feb  3 19:25:27 2020', 1580783127.7323301]
#VVT: Attrs = {}

{'name': 'at', 'params': {'np': '1'}, 'attrs': {'xdate': 1580783127.73, 'state': 'notdone', 'timeout': 3600, 'xtime': -1}, 'keywords': ['foo', 'bar'], 'path': 'at.vvt', 'root': '/scratch/rrdrake/temp/prob/analyze'}
{'name': 'at', 'params': {'np': '1'}, 'attrs': {'xdate': 1580783127.73, 'state': 'done', 'timeout': 3600, 'xtime': 1, 'result': 'pass'}, 'keywords': ['foo', 'bar'], 'path': 'at.vvt', 'root': '/scratch/rrdrake/temp/prob/analyze'}

#VVT: Finish = ['Mon Feb  3 19:25:28 2020', 1580783128.7356429]
"""


############################################################################

def create_TestCase():
    ""
    ts = TestSpec.TestSpec( 'atest', os.getcwd(), 'atest.xml' )

    ts.setKeywords( ['key1','key2'] )

    ts.setParameters( { 'P1':'V1', 'P2':'V2' } )

    ts.setAttr("aname1", "a value")
    ts.setAttr("aname2", "a\nvalue")
    ts.setAttr("aname3", 'a"value"')
    ts.setAttr("aname4", "a'value'")
    ts.setAttr('aname5', 23)
    ts.setAttr('aname6', 23.23)
    ts.setAttr('aname7', None)

    return TestCase( testspec=ts )


def assert_TestCase_same_as_fake( tcase, rootdir=None ):
    ""
    if not rootdir:
        rootdir = os.getcwd()

    tspec = tcase.getSpec()

    assert tspec.getName() == 'atest'
    assert tspec.getRootpath() == rootdir
    assert tspec.getFilename() == os.path.join( rootdir, 'atest.xml' )

    kL = tspec.getKeywords( include_implicit=False )
    kL.sort()
    assert kL == [ 'key1', 'key2' ]

    kL = tspec.getKeywords()
    kL.sort()
    assert kL == [ 'P1', 'P2', 'atest', 'key1', 'key2' ]

    pD = {}
    for n,v in tspec.getParameters().items():
        pD[n] = v
    assert pD == { 'P1':'V1', 'P2':'V2' }

    assert tspec.getAttr('aname1') == "a value"
    assert tspec.getAttr('aname2') == 'a\nvalue'
    assert tspec.getAttr('aname3') == 'a"value"'
    assert tspec.getAttr('aname4') == "a'value'"
    assert tspec.getAttr('aname5') == 23
    assert tspec.getAttr('aname6') == 23.23
    assert tspec.getAttr('aname7') == None


def create_TestCase_with_results():
    ""
    tcase = create_TestCase()

    tcase.getStat().markStarted( time.time() )

    return tcase


def create_fake_analyze_TestCase():
    ""
    tspec = TestSpec.TestSpec( 'atest', os.getcwd(), 'atest.vvt' )

    pset = ParameterSet.ParameterSet()
    pset.addParameter( 'A', ['a1','a2'] )
    tspec.setParameterSet( pset )

    tcase = TestCase( tspec )

    assert tcase.getSpec().isAnalyze()

    return tcase


def write_test_list_with_include( testfile, inclpath, finish=True ):
    ""
    d = os.path.dirname( inclpath )
    if d and not os.path.exists(d):
        os.mkdir( d )
        time.sleep(1)

    tlw = tio.TestListWriter( testfile )
    tlw.start()
    tlw.addIncludeFile( inclpath )

    write_test_list_with_fake_test( inclpath )

    if finish:
        tlw.finish()


def get_single_test_from_test_list( testlist ):
    ""
    tD = testlist.getTests()
    assert len(tD) == 1
    tcase = list( tD.values() )[0]
    return tcase


def write_test_list_with_fake_test( filename, **kwargs ):
    ""
    tlw = tio.TestListWriter( filename )
    tlw.start()
    tcase = create_TestCase()
    for k,v in kwargs.items():
        tcase.getSpec().setAttr( k, v )
    tlw.append( tcase )
    tlw.finish()


def write_test_sequence_to_file( filename, tcase ):
    ""
    tlw = tio.TestListWriter( filename )
    tlw.start()

    tcase.getStat().markStarted( time.time() )
    tlw.append( tcase )

    tcase.getStat().markDone( 0 )
    tlw.append( tcase )

    tlw.finish()


def write_TestList_with_fake_test( addrundate=False, **kwargs ):
    ""
    tl = TestList.TestList()

    if addrundate:
        tl.setResultsSuffix()

    tcase = create_TestCase()
    for k,v in kwargs.items():
        tcase.getSpec().setAttr( k, v )
    tl.addTest( tcase )

    if addrundate:
        tl.stringFileWrite( extended=True )
    else:
        tl.stringFileWrite()

    return tl


def write_TestList_fake_results( testlistobj ):
    ""
    rfile = testlistobj.initializeResultsFile()
    tcase = create_TestCase_with_results()
    testlistobj.appendTestResult( tcase )
    testlistobj.writeFinished()

    return rfile


def read_TestList_and_check_fake_test():
    ""
    tl = TestList.TestList()
    tl.readTestList()
    tl.readTestResults()
    tL = list( tl.getTests() )
    assert len(tL) == 1
    assert_TestCase_same_as_fake( tL[0] )


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
