#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3


class prologue_epilogue_plugin_tests( vtu.vvtestTestCase ):

    def test_calling_prologue(self):
        ""
        plug = vtu.make_user_plugin( """
            def prologue( cmdline ):
                ""
                print ( ' '.join(cmdline) )
            """ )

        rtn,out,err = util.call_capture_output( plug.callPrologue,
                                                ['foo','--bar'] )

        assert out.strip() == 'foo --bar'
        assert not err.strip()

    def test_calling_prologue_with_an_exception(self):
        ""
        plug = vtu.make_user_plugin( """
            def prologue( cmdline ):
                ""
                raise Exception( 'fake exception' )
            """ )

        rtn,out,err = util.call_capture_output( plug.callPrologue,
                                                ['foo','--bar'] )
        assert 'fake exception' in out

        plug.callPrologue( ['foo','--bar'] )

    def test_calling_epilogue(self):
        ""
        plug = vtu.make_user_plugin( """
            def epilogue():
                ""
                print ( 'done done done' )
            """ )

        rtn,out,err = util.call_capture_output( plug.callEpilogue )

        assert out.strip() == 'done done done'
        assert not err.strip()

    def test_calling_epilogue_with_an_exception(self):
        ""
        plug = vtu.make_user_plugin( """
            def epilogue():
                ""
                raise Exception( 'fake exception' )
            """ )

        rtn,out,err = util.call_capture_output( plug.callEpilogue )
        assert 'fake exception' in out

        plug.callEpilogue()

    def test_prologue_epilogue_integration(self):
        ""
        util.writefile( 'testA.vvt', """
            pass
            """ )
        util.writefile( 'adir/vvtest_user_plugin.py', """
            def prologue( cmdline ):
                ""
                print ( 'CMDLINE='+' '.join( cmdline ) )

            def epilogue():
                ""
                print ( 'EPILOGUE=foobar' )
            """ )
        adir = os.path.abspath( 'adir' )
        time.sleep(1)

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( '-vv --config', adir, batch=batch )
            vrun.assertCounts( total=1, npass=1 )

            assert 'CMDLINE=' in vrun.out and '-vv --config' in vrun.out
            assert 'EPILOGUE=foobar' in vrun.out


############################################################################

util.run_test_cases(sys.argv, sys.modules[__name__])
