#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
from os.path import abspath
from os.path import join as pjoin
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3

from libvvtest.filtering import TestFilter


class device_tests( vtu.vvtestTestCase ):

    def test_filtering_out_tests_by_max_cpu_cores(self):
        ""
        tcase1 = vtu.make_fake_TestCase()
        tcase1.getSpec().setParameters( { 'np':'1' } )

        tcase2 = vtu.make_fake_TestCase()
        tcase2.getSpec().setParameters( { 'np':'4' } )

        rtc = vtu.make_RuntimeConfig()
        rtc.setMaxSize( (1,0) )
        tf = TestFilter( rtc, None )
        assert tf.checkMaxProcessors( tcase1 )
        assert not tf.checkMaxProcessors( tcase2 )

        rtc.setMaxSize( (1,4) )
        assert tf.checkMaxProcessors( tcase1 )
        assert not tf.checkMaxProcessors( tcase2 )

        rtc.applyMaxSizeExpression( False )
        assert tf.checkMaxProcessors( tcase1 )
        assert tf.checkMaxProcessors( tcase2 )

    def test_filtering_out_tests_by_max_devices(self):
        ""
        tcase1 = vtu.make_fake_TestCase()
        tcase1.getSpec().setParameters( { 'np':'1', 'ndevice':'0' } )

        tcase2 = vtu.make_fake_TestCase()
        tcase2.getSpec().setParameters( { 'np':'1', 'ndevice':'1' } )

        tcase3 = vtu.make_fake_TestCase()
        tcase3.getSpec().setParameters( { 'np':'1', 'ndevice':'4' } )

        rtc = vtu.make_RuntimeConfig()
        rtc.setMaxSize( (1,0) )
        tf = TestFilter( rtc, None )
        assert tf.checkMaxProcessors( tcase1 )
        assert not tf.checkMaxProcessors( tcase2 )
        assert not tf.checkMaxProcessors( tcase3 )

        rtc.applyMaxSizeExpression( False )
        assert tf.checkMaxProcessors( tcase1 )
        assert tf.checkMaxProcessors( tcase2 )
        assert tf.checkMaxProcessors( tcase3 )

        rtc = vtu.make_RuntimeConfig()
        rtc.setMaxSize( (1,1) )
        tf = TestFilter( rtc, None )
        assert tf.checkMaxProcessors( tcase1 )
        assert tf.checkMaxProcessors( tcase2 )
        assert not tf.checkMaxProcessors( tcase3 )

        rtc = vtu.make_RuntimeConfig()
        rtc.setMaxSize( (1,4) )
        tf = TestFilter( rtc, None )
        assert tf.checkMaxProcessors( tcase1 )
        assert tf.checkMaxProcessors( tcase2 )
        assert tf.checkMaxProcessors( tcase3 )

    def test_run_a_test_using_two_devices(self):
        ""
        util.writefile( 'config/idplatform.py', """
            def platform( opts ):
                if '--plat' in opts:
                    return opts['--plat']
                else:
                    return 'GPUstacks'
            """ )
        util.writefile( 'config/platform_plugin.py', """
            def initialize( plat ):
                if plat.getName() == 'GPUstacks':
                    plat.setattr( 'maxdevices', 4 )
            """ )

        util.writefile( 'atest.vvt', """
            #VVT: parameterize : ndevice = 2 8
            import vvtest_util as vvt
            print ( 'np_ids='+repr(vvt.RESOURCE_IDS_np) )
            print ( 'np_tot='+repr(vvt.RESOURCE_TOTAL_np) )
            print ( 'device_ids='+repr(vvt.RESOURCE_IDS_ndevice) )
            print ( 'device_tot='+repr(vvt.RESOURCE_TOTAL_ndevice) )
            """ )
        time.sleep(1)

        vrun = vtu.runvvtest( '-n 1 -N 5 --devices 4' )
        vrun.assertCounts( total=1, npass=1 )
        self.check_resource_output( vrun )

        vtu.remove_results()

        vrun = vtu.runvvtest( '--plat GPUstacks --batch --config config' )
        vrun.assertCounts( total=1, npass=1 )
        self.check_resource_output( vrun )

    def check_resource_output(self, vrun):
        ""
        sval = vrun.greplogs( 'np_ids=' )[0]
        npids = eval( sval.split( 'np_ids=' )[1].strip() )
        assert len( npids ) == 1 and npids[0] >= 0

        sval = vrun.greplogs( 'np_tot=' )[0]
        nptot = eval( sval.split( 'np_tot=' )[1].strip() )
        assert nptot > 0

        sval = vrun.greplogs( 'device_ids=' )[0]
        ndids = eval( sval.split( 'device_ids=' )[1].strip() )
        assert len( ndids ) == 2
        assert ndids[0] >= 0 and ndids[1] >= 0 and ndids[0] != ndids[1]

        sval = vrun.greplogs( 'device_tot=' )[0]
        ndtot = eval( sval.split( 'device_tot=' )[1].strip() )
        assert ndtot == 4


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
